"""NBACore v8 §2 Layer 3 — API routers package."""
from backend.api.routers import (
    batch,
    charts,
    clutch,
    clutch_replay,
    context,
    crawler,
    data_import,
    export,
    games,
    intelligence,
    leaderboard,
    metrics,
    monitor,
    players,
    system,
    teams,
    trade,
    tactics,
    vs,
    workspace,
)

__all__ = [
    "batch",
    "charts",
    "clutch",
    "clutch_replay",
    "context",
    "crawler",
    "data_import",
    "export",
    "games",
    "intelligence",
    "leaderboard",
    "metrics",
    "monitor",
    "players",
    "system",
    "teams",
    "trade",
    "tactics",
    "vs",
    "workspace",
]
