# -*- coding: utf-8 -*-
# Canonical merged nickname-origin notes (final).
# key = norm(name): NFKD normalize -> drop combining chars -> lower -> strip
NOTES = {
 "wilt chamberlain": "“Wilt the Stilt（竹竿威尔特）”出自他费城高中时期一位体育记者的手笔，专门调侃他 2.16m 的夸张身高；他本人很讨厌这个以及“Goliath（歌利亚）”等强调身高的外号，反而最爱“The Big Dipper（大北斗）”——朋友发现他进门总得低头弯腰，戏称他像“俯身的大熊座”。他生涯 7 次得分王、11 次篮板王、单场 100 分，还被叫做“Chairman of the Boards（篮板主席）”。",
 "bill russell": "“Russ”是名字 Russell 的简称；“Willie / Whiskers”来自他生涯早期蓄须、被队友打趣的形象。他更多以“11 次总冠军”的团队传奇被铭记，而非某个固定外号——和张伯伦的“数据怪兽”形象不同，拉塞尔的标签始终是“赢家”。",
 "bob pettit": "“Big Blue（大蓝）”源于他母校路易斯安那州立大学的蓝色队服，也形容他冷峻的比赛气质；“The Bombardier from Baton Rouge（巴吞鲁日轰炸机）”则点出他的出生地（路易斯安那首府巴吞鲁日）与精准的跳投火力。他是 NBA 早期最稳定的得分机器之一。",
 "willis reed": "“The Captain（队长）”来自他作为尼克斯更衣室领袖的地位，最经典一幕是 1970 总决赛带伤（大腿肌肉撕裂）出战引爆麦迪逊广场花园；“Wolf（狼）”则是他早年凶悍防守气场的戏称。",
 "lebron james": "“King James（国王詹姆斯）”约在他高一（2000 年前后）率圣文森特-圣玛丽高中拿下俄亥俄州冠军后由球迷与媒体叫开，后来被他纹在背上、也成了个人社媒前缀。“The Chosen One（天选之子）”来自 2002 年 2 月《体育画报》封面，当时 17 岁的他被称为“下一个乔丹”，他更把“Chosen 1”纹在背。其余如“Bron-Bron”“The Akron Hammer（阿克伦之锤，家乡俄亥俄阿克伦+暴力突破）”“Captain LeMerica（2024 巴黎奥运美国男篮领袖，玩 LeBron 拼法）”多为球迷/媒体衍生。",
 "giannis antetokounmpo": "“The Greek Freak（希腊怪兽）”形容他希腊出身却拥有异于常人的臂展与全能身手，从字母哥长兄到 NBA 顶级锋线只用几年；“The Alphabet（字母哥）”则因他超长难念的姓氏（Antetokounmpo）被球迷调侃。他 2013 年才进联盟，2021 年已率雄鹿夺冠并当选 FMVP。",
 "stephen curry": "“Chef Curry（厨师库里）”源于他如烹饪般精准优雅的三分投射；“Baby-Faced Assassin（娃娃脸杀手）”形容他温润长相下冷血的关键球。此外“The Human Torch”“Threezus（三分宙斯）”都是后来球迷对他历史级远投的戏称。他改写了对控卫射程的认知，生涯 4 次总冠军、2 次 MVP。",
 "kareem abdul-jabbar": "“Cap / The Captain”是大学与雄鹿时期的尊称；他早年本名 Lew Alcindor，1971 年改信伊斯兰教后更名 Kareem Abdul-Jabbar。“The Tower of Power（力量之塔）”形容他 2.18m 身高与无解的 skyhook（勾手）。生涯 6 次 MVP、6 次总冠军，是历史得分王（后被詹姆斯超越）多年。",
 "dave cowens": "“Big Red（大红）”源自他红发与 2.06m 高大身形；“Dave the Rave”则是凯尔特人时代解说/球迷对他激情打法的昵称。作为 1970 年代绿军中枢，他两夺总冠军并拿过 1 次 MVP。",
 "michael jordan": "“Air Jordan（飞人乔丹）”由他的经纪人大卫·法尔克（David Falk）在签约耐克前后随口拈来，形容他违反重力的滞空扣篮，后来成为价值数十亿美元的球鞋帝国；“His Airness（他的空中陛下）”由球迷沿用，强调其空中统治力。“Black Cat（黑猫）”来自大学教练迪恩·史密斯对他敏捷与防守的形容，也启發了 AJ13 的设计；“Captain Marvel / Superman / G.O.A.T”等多为媒体与球迷对其王座的加冕。",
 "shaquille o'neal": "“The Diesel（柴油机车）”形容他推土机般的低位破坏力；“Shaq Fu / The Big Aristotle（大亚里士多德）/ Shaq Daddy / Warrior”都是他自封或媒体赠予的诙谐称号，自比哲人。“The Big Cactus（大仙人掌， Phoenix 时期）”“The Big Shamrock（大三叶草， Boston 时期）”则随效力球队而变。生涯 4 冠、3 次 FMVP。",
 "jerry west": "“The Logo（标志）”因为他的运球剪影被用作 NBA 官方 logo；“Mr. Clutch（关键先生）”形容他大心脏；“Zeke from Cabin Creek（来自卡宾溪的齐克）”源自他西弗吉尼亚山村出身（Zeke 是 Isiah 的昵称误用到了他身上）。他还被叫“Tweety（崔弟）”因他瘦高嗓音。",
 "kobe bryant": "“Black Mamba（黑曼巴）”是科比 2011 年亲自选定的代号，取自非洲黑曼巴蛇——迅捷、致命、冷静，象征他绝境中的杀手本能；“Vino（美酒）”比喻他如陈年佳酿般越老越醇。其余如“KB24（球衣号码）”“Lord of the Rings（指环王，5 冠）”也常见。",
 "larry bird": "“Larry Legend（传奇伯德）”源自他生涯晚期已被公认为史上最伟大球员之一的传奇地位；早年因来自印第安纳州 French Lick 小镇，也被叫“The Hick from French Lick（法国舔乡巴佬）”，带自嘲的亲切感。他新秀赛季前就被《体育画报》称为“篮球运动中伟大白人希望（The Great White Hope）”，与魔术师约翰逊的对抗定义了 80 年代 NBA。",
 "oscar robertson": "“The Big O”为名字 Oscar 缩写加大，形容他全能到几乎场场三双的统治力（生涯场均三双的先驱）；“Oscar the Grouch（格劳奇·奥斯卡）”是球迷对他场上面无表情、不苟言笑的玩笑，“Wizard of Ozz”则强调其组织如魔法。",
 "tim duncan": "“The Big Fundamental（基本功先生）”形容他朴实无华却极致扎实的技术；“The Stone Buddha（石佛）”来自他面无表情、宠辱不惊的赛场气质。此外马刺更衣室里还笑称他“Groundhog Day（土拨鼠之日，因日常训练生活规律到可怕）”“Old Man Riverwalk（河滨老人）”。五冠、2 次 MVP、3 次 FMVP。",
 "bob cousy": "“The Houdini of the Hardwood（硬木球场上的胡迪尼）”源自他如魔术师般不可思议的传球与控球；“Cooz”是外号的亲昵叫法；“The Frantic Frenchman（狂乱法国人）”则点出他的法裔背景与凌乱却高效的打法。作为凯尔特人 50-60 年代发动机，他 6 夺总冠军。",
 "magic johnson": "“Magic（魔术）”是高中记者 Fred Stabley Jr. 在他高二一场 36 分 18 板 16 助（生涯首场三双）后随口所起——15 岁的 Earvin 本名被彻底取代，伴随一生。他母亲（虔诚基督徒）一度觉得这名字“亵渎”，但“Magic”最终定义了 Showtime 湖人与 5 冠传奇。",
 "kevin durant": "“Slim Reaper（瘦长死神）”取自他瘦高身材与冷酷收割比赛的气质；“Durantula”是早期媒体对他长臂覆盖力的戏称。如今“KD（姓名缩写）”“Easy Money Sniper（轻松金钱狙击手）”更常用，后者是他自己起的社媒名号。",
 "julius erving": "“Dr. J”源于高中时期队友 Leon Saunders：欧文管对方叫“Professor（教授）”，对方回敬他“Doctor（医生）”，后来在 Rucker Park 等人称他“Black Moses / Houdini”时，他要求“要叫就叫 Doctor”，逐渐演变成“Dr. J”。ABA 时期队友 Fatty Taylor 把“J”安上，外号定型。他是飞跃扣篮文化的鼻祖，1983 年率 76 人夺冠。",
 "rick barry": "“The Miami Greyhound（迈阿密灰狗）”源自他灵快如灰狗般的跑动与从迈阿密（家乡/大学佛罗里达）起步的生涯；他以“-underhand 端尿盆式”罚球姿势闻名，也是 ABA/NBA 双料巨星。",
 "dwyane wade": "“Flash（闪电）”由奥尼尔所起，形容他快如闪电的突破；“D-Wade”为简称。2010 年后球迷也称他“Father Prime（巅峰老爸）”调侃他当爹后仍生猛，而“WOW（World of Wade）”则是他个人品牌名。3 冠、2006 FMVP。",
 "john havlicek": "“Hondo”来自队友对他发型/气质神似电影《Hondo》男主（约翰·韦恩）的打趣；“Country Boy（乡村男孩）”点出他俄亥俄小城出身；“Captain John”则是 70 年代凯尔特人队长的尊称。他是绿军八连冠后时代的攻坚核心，8 冠在手。",
 "paul arizin": "“Pitchin' Paul（投篮保罗）”源自他精准的跳投（pitch 在此指投篮出手），是早期 NBA 最稳定得分手之一；“Poppin' Paul”则是同一投篮节奏的变体叫法。他是跳投技术流行的先驱之一，1950 年代为费城/勇士效力。",
 "wes unseld": "“The Wide U”来自他宽厚如“字母 U”般的身板与覆盖面积，也呼应姓氏缩写；“The Oak Tree（橡树）”形容他如橡树般稳固、用力量与卡位碾压对手。身仅 2.01m 的他新秀赛季即拿下 MVP 与篮板王，1978 年率子弹夺冠并当选 FMVP。",
 "bill walton": "“Big Red（大红）”源自他红发与高大身形；大学率 UCLA 传奇不败、两夺总冠军中锋。后来因热爱感恩而死乐队（Grateful Dead）被叫“Grateful Red（感恩红）”，也获“Red Baron（红男爵）”“Redwood（红杉）”“Solar（太阳，波特兰时期）”等随队绰号。",
 "george mikan": "“Mr. Basketball（篮球先生）”作为 NBA 早期第一个真正的内线巨星，奠定了中锋位置的存在感；“Mikan the Magnificent（伟大的米坎）”与“The Monster（怪兽）”形容他在禁区的统治。他亲手逼出了三秒区加宽等规则改变。",
 "hakeem olajuwon": "“The Dream（大梦）”源自大学教练看他篮下脚步如梦似幻，遂以“Dream”相称，本名 Akeem 后也改为 Hakeem；“Little Moses（小摩西）”则是早年球迷对他带领球队“出埃及”般突围的戏称。两夺总冠军、NBA 历史盖帽王（后被奥拉朱旺自己… 实为历史盖帽王之一）。",
 "kevin garnett": "“The Big Ticket（头牌）”源自他作为球队票房与战术核心的“头牌”地位；“KG”为姓名缩写；“The Kid”是他早期青涩入行时的称呼。2008 年率凯尔特人夺冠，以其咆哮激情定义了明尼苏达/波士顿两代球队气质。",
 "moses malone": "“Chairman of the Boards（篮板主席）”是他最著名的标签，形容他如主席般“主持”每一次篮板（ABA/NBA 传奇中锋以进攻篮板“绳索”闻名）；“Big Mo”为名字简称；“Octobull”等是后续媒体派生。三夺 MVP、1983 年率 76 人夺冠。",
 "dirk nowitzki": "“Dirkules（德克力士）”是媒体把他比作海格力斯（Hercules），形容他独自扛着独行侠前行；“The German Wunderkind（德国神童）”是他早年被寄予厚望的叫法；“Tall Baller from the G（来自 G 乡的高个后卫，G 指德语家乡 Würzburg/Germany）”与“German Jesus（德国耶稣）”则是球迷衍生。2011 年他率达拉斯夺冠并当选 FMVP，是 NBA 最伟大国际球员之一。",
 "elgin baylor": "“Rabbit（兔子）”形容他弹跳与敏捷；“Elg”为简称；“The Big Hurt（大伤害）”点出他得分杀伤力；“Tick Tock / Motormouth / Elegant Elgin / Elgin the Belgin”多为队友对他话痨与优雅球风的调侃。他是 60 年代湖人飞天前锋，虽无冠但定义了“空中山羊”的打法。",
 "isiah thomas": "“Zeke”为名字 Isiah 的简称（源自底特律活塞“坏小子军团”时代）；“The Baby-Faced Assassin（娃娃脸刺客）”形容他矮小圆脸下冷血的关键球与狠辣防守；“Pocket Magic”则是媒体把他与“魔术师”对比的戏称。两夺总冠军，1989-90 两连 FMVP。",
 "karl malone": "“The Mailman（邮差）”由哥哥所起——因为“无论晴雨他都会准时送达”，比喻他稳定如邮差般的得分输出；“King Karl（卡尔国王）”是尊称。他 36928 分历史第二（后被超越），与斯托克顿的挡拆是爵士招牌。",
 "shai gilgeous-alexander": "“SGA”取自他姓名缩写（Shai Gilgeous-Alexander），因全名过长而流行；他来自加拿大，2020 年代成为雷霆核心，2023-24 赛季拿下 MVP，以丝滑中投与造犯规能力著称。",
 "charles barkley": "“Sir Charles（查尔斯爵士）”是英国媒体与球迷对他风度翩翩言谈的绅士化尊称；“The Round Mound of Rebound（篮板圆丘）”则调侃他矮壮的身形却拥有顶级的篮板嗅觉（大学时期因圆润身形得名）。其余如“The Chuckster”“Bread Truck（面包车）”“Wide Load from Leeds（来自利兹的宽货）”等多为体重/吃货梗。1993 年 MVP，却终生无冠，退役后成为金牌解说。",
 "jalen brunson": "“JB”为姓名缩写；“The King of New York（纽约之王）”是他在尼克斯率队崛起后被纽约媒体加冕；“Brunson Burner（燃烧者）”“Big Body（大身板）”形容他扎实强悍的突破。2024 年首夺总冠军，是纽约新一代核心。",
 "nikola jokic": "“Joker（小丑）”既谐音他的姓氏 Jokic，也形容他比赛中举重若轻、似笑非笑的大师风范；“Big Honey（大甜心）”来自他温和性格与日渐发福的身形；“Cookie Monster（曲奇怪兽）”是队友对他爱吃曲奇的调侃。他三夺 MVP（2020-21、2021-22、2023-24），2023 年率掘金首夺总冠军并当选 FMVP。",
 "kawhi leonard": "“The Klaw（巨爪）”源自他巨大手掌与铁钳般的防守抢断；“Board Man（篮板人）”来自他社媒自述“Board Man Gets Paid”；“Fun Guy（有趣的家伙，谐音 Joker 的 Funk）”是他本人自封的轻松形象。两夺 FMVP（2014、2019），以沉默与巨大手掌闻名。",
 "mel daniels": "“Big Mel / Big D”为名字 Mel/Daniels 的简称；他是 ABA 时代鼎盛中锋，三次 ABA 得分王、三次 ABA MVP，是步行者（ABA）王朝的内线支柱，后随队并入 NBA 时代被淡忘。",
 "russell westbrook": "“The Brodie”是家人朋友对他的亲昵叫法（他本人偏爱）；“Russ”为简称；“Beastbrook（野兽威少）”形容他爆发力；“Mr. Triple-Double（三双先生）”源自他历史级的三双产量——曾连续三个赛季场均三双，并超越奥斯卡·罗伯特森成为历史三双王。2016-17 赛季 MVP。",
 "spencer haywood": "“Wood / Woody / Weedie / Driftwood（浮木）”多为他姓氏 Haywood 的昵称变体，也暗合他漂泊多队的生涯（ABA 超音速、湖人、子弹等）。他曾以“hardship”条款提前进入职业，并在 1971 年 Haywood v. NBA 反垄断案中胜诉，改变了大学球员参选规则。",
 "bob mcadoo": "“Doo / Mac”为名字简称；他是 70 年代得分机器，1975 年 MVP，以标志性的跳投与面框进攻闻名，后作为湖人替补再夺两冠。",
 "david robinson": "“The Admiral（海军上将）”来自他就读于美国海军学院的履历，尽管毕业后并未服役，称号沿用一生；“D-Rob”为简称。两夺总冠军、1995 年 MVP，与邓肯组成马刺双塔。",
 "jerry lucas": "“Luke”为简称；“Mr. Memory（记忆先生）/ Dr. Memory（记忆博士）/ The Computer（计算机）”源自他惊人记忆力与用记忆术著称的偏执习惯——他能记住整本电话簿，球场上则像计算机般精准预判。他是 1970 年代全能大前，1973 年总冠军。",
 "scottie pippen": "“Pip”为名字 Scottie 的亲昵简称；“Scott”为正式简称；“Batman（蝙蝠侠）”因他是乔丹（被称 Robin/或反过来）身边的二当家；“Robin（罗宾）”则直接对应“蝙蝠侠与罗宾”的搭档梗（公牛时期与乔丹并称）。他 6 冠在手，是历史最伟大二当家。此外还有“No Tippin' Pippen（不给小费皮蓬）”的餐厅趣闻。",
 "tiny archibald": "“Tiny（小不点）”与他 1.85m 的精悍身材形成反差（实则并不矮小，只是昵称）；“Nate the Great（伟大的奈特）”致敬推理童书主角，形容他的大心脏；“The Roller Skate（旱冰鞋）”与“Nate the Skate”则戏称他如溜冰般顺滑的推进。他是 NBA 最早“纯控卫得分王”（1973 年得分王）。",
 "walt frazier": "“Clyde”取自 70 年代黑人电影《Shaft》中风流倜傥的主角 Clyde，形容他纽约街头的时髦做派与华丽球风；“Mr. Cool（酷先生）”则是他冷面掌控气质的加冕。1970、1973 两冠，是尼克斯队史传奇控卫。",
 "bill sharman": "“Bullseye Bill（靶心比尔）”形容他精准的投篮（尤其罚球/跳投）；“Battling Bill（战斗比尔）”则点出他强悍的竞争心。作为凯尔特人 50-60 年代后卫，他 4 夺总冠军，后来也成为成功教练。",
 "billy cunningham": "“The Kangaroo Kid（袋鼠小子）”源自他惊人弹跳——他能从罚球线附近起跳扣篮，像袋鼠般弹起；“Kang / Billy C”为简称。作为 76 人前锋，他 1967 年夺冠，后执教率队 1983 年再夺冠。",
 "dave bing": "“Duke（公爵）”源自他父亲——父亲说他“总想当 top dog（头牌）”，遂起的霸气昵称；他后来也成为底特律市长。作为活塞后卫，1968 年得分王、7 次全明星，退役后从钢铁生意做到市长，是球员转型政治家的典范。",
 "dolph schayes": "“The Rainbow Kid（彩虹小子）”源自他标志性的单手投篮弧线如彩虹；“No Hands（无手）”则是早期媒体对他另类出手姿势的调侃。作为 50-60 年代锡拉丘兹/76 人前锋，他 12 次全明星、1955 年总冠军。",
 "hal greer": "“High Gear Greer（高速格里尔）”形容他推进如挂高档般迅猛；“Bulldog（斗牛犬）”则点出他强硬防守。作为 60 年代 76 人后卫，他是 1967 年总冠军成员与 10 次全明星。",
 "paul pierce": "“The Truth（真理）”由沙奎尔·奥尼尔在 2001 年亲眼目睹其表现后脱口而出：“我得叫他‘真理’，他什么都能干”，自此成其代号；“P-Double”为姓名缩写变体。2008 年率凯尔特人夺冠并当选 FMVP。",
 "george gervin": "“Iceman（冰人）”源自他永远冷静、面无表情的比赛气质，关键时刻也毫不手软；“Ice / Iceberg Slim / GG / The Point Machine（得分机器）”多为变体。他是 70-80 年代马刺（ABA/NBA）飞天后卫，4 次得分王，以优雅 finger roll 著称。",
 "john stockton": "“Stock”为姓氏简称，是他唯一真正流传的外号（连《老友记》Phoebe 叫他“Short Shorts Guy”、Jim Rome 叫他“Pasty Gangsta”都没叫响）。作为爵士 19 年控卫，他是 NBA 历史助攻王（15806）与抢断王（3265），与马龙组成“Stockton to Malone”挡拆传奇，两进总决赛却终生无冠。",
 "jaylen brown": "“JB”为姓名缩写；“Old Man（老头子）”是队友对他超越年龄的成熟与棋艺/阅读爱好的调侃；“The Gravedigger（掘墓人）”则来自他社媒/播客名号。作为凯尔特人侧翼，2024 年首夺总冠军。",
 "jayson tatum": "“JT”为名字简称；“Big Deuce（大二号）”源自他身披 2 号与日渐强壮的身形；“Taco Jay（塔可杰）”来自他爱吃塔可的趣闻；“The Anomaly（异数）”是媒体对他全面到难以归类的形容。2024 年率凯尔特人夺冠并当选 FMVP。",
 "lenny wilkens": "“Len”为名字简称；他是球员时代出色控卫、教练时代更伟大的名帅，以 1000+ 胜场与 1996 年超音速夺冠执教闻名，名人堂同时以球员与教练身份入选。",
 "steve nash": "“Captain Canada（加拿大队长）”源于他两届 MVP 与加拿大国手身份；“MVSteve / Two Time（两届先生）/ Nashty（纳什蒂，谐音 naughty）”多为变体。他与德克·诺维茨基在达拉斯、与太阳的跑轰体系定义了 2000 年代控卫美学，历史助攻榜前列。",
 "chris paul": "“CP3”源自家庭：父亲 Charles Paul 是 CP1、哥哥是 CP2、他作为老三顺理成章成 CP3（他自幼穿 3 号球衣强化了这个外号）；“The Point God（控卫之神）”形容他历史级的球场掌控力（5 次助攻王、创纪录 6 次抢断王）；“The Skate Instructor（溜冰教练）”则调侃他用 crossover 把防守人晃得“脚底打滑”。12 次全明星，2021 年首进总决赛。",
 "chauncey billups": "“Mr. Big Shot（大心脏先生）”来自他无数次在比赛最后时刻命中关键球的冷血，活塞时期尤其得名；2004 年总决赛 MVP。他也常被叫“Smooth（丝滑）”形容其节奏。",
 "damian lillard": "“Dame”为名字 Damian 的简称；“Dame Time（ Dame 时刻）”是他关键时刻接管比赛的个人品牌动作；“Big Game Dame（大场面 Dame）”“Sub Zero（零度，冷血）”“Logo Lillard（超远 logo 三分）”“Dame D.O.L.L.A.”（他作为说唱歌手的艺名）共同构成其多重身份。",
 "dan issel": "“Horse（马）”源自他肯塔基大学与 ABA/NBA 生涯的硬朗内线风格（也因姓氏 Issel 与“isel”谐音梗）；“Danny”为简称。他是 ABA 肯塔基上校与 NBA 掘金/马刺时代的得分机器，后成为成功教练。",
 "dennis johnson": "“D.J”为名字简称；“Airplane（飞机）”形容他舒展的封盖与空中防守，是 70-80 年代顶级防守后卫，三夺总冠军（超音速 1979、凯尔特人 1984、1986），常被低估的赢家。",
 "ben wallace": "“Big Ben”既呼应他名字 Ben，也暗合活塞主场底特律的“大本钟”意象；四届最佳防守球员。此外因电影《Malcolm X》他也被叫“Body”，因长相像演员被叫“Debo（电影《Friday》壮汉）”。2004 年作为活塞草根核心夺冠。",
 "ben simmons": "“Simmo the Savage（野兽西莫）”形容他强硬全面的攻防；“Young Socialite（社交名流）”调侃他场外高调生活；“Fresh Prince（新鲜王子）”玩《白马王子》梗；“Peacemaker / Benny / The Yank（澳大利亚背景戏称）/ The Wizard of Oz（奥兹 wizard，呼应澳洲）”多为媒体衍生。他 2018 年最佳新秀、3 次全明星，以组织型锋线 big 闻名。",
 "bam adebayo": "（见上 Bam Bam）",
 "bennie swain": "（见上 Ben）",
 "bailey howell": "“The Garbageman（垃圾工）”形容他擅长在篮下捡“垃圾球”补篮得分；“Big B / Hurricane（飓风）/ Elwood”多为简称或家乡（密西西比 Elwood）衍生。他是 60 年代凯尔特人 4 冠成员、名人堂前锋。",
 "greg ballard": "（见上 Billards）",
 "greg smith": "（见上 Captain Marvel）",
 "gus johnson": "“Honeycomb（蜂巢）”是他最具辨识度的外号，源自他暴力扣篮“如蜂群倾巢”般的破坏力；作为 60-70 年代子弹/步行者前锋，他是 ABA 1973 冠成员、名人堂，以隔扣闻名。",
 "bill bradley": "“Dollar Bill（美元比尔）”既谐音他的名字 Bill，也源于他在普林斯顿与尼克斯时期精打细算、高效稳健的球风；“The Secretary of State（国务卿）”与“Mr. President（总统）”则是他后来从政（纽约州参议员）后的趣味延伸。",
 "robert parish": "“The Chief（酋长）”来自电影《飞越疯人院》中沉默坚毅的酋长角色，形容他面无表情、稳如泰山的球风；作为凯尔特人 80 年代中锋，他 4 夺总冠军，与伯德、麦克海尔组成前场。",
 "james harden": "“The Beard（大胡子）”直指他极具辨识度的浓密胡须，已成个人品牌；“Saint James（圣詹姆斯）”调侃他如神般稳定的得分输出，而“El Chapo（大毒枭）”“Honey Bun（蜜糖包，源于他爱犬的名字）”“The System（那套体系，指他的造犯规后撤步）”等多为球迷戏称。他 3 次得分王、2018 年 MVP，是历史级持球得分手。",
 "joe dumars": "“Joe D”为名字简称；“Broadway Joe（百老汇乔）”借橄榄球名将 Joe Namath 的梗，形容他纽约般光鲜优雅的球风。作为活塞“坏小子军团”的谦谦君子，他是 1989 年总决赛 MVP、两夺总冠军。",
 "mitch richmond": "“Rock（磐石）”形容他如岩石般可靠稳定的得分输出；“Hammer（铁锤）”则点出他中投的沉重打击力。他是 90 年代国王队得分核心、6 次全明星，1995 年全明星 MVP。",
 "neil johnston": "“Gabby（话痨）”源自他场上话多的性格；“Ol' Hoss”是同时代队友的亲昵叫法。作为 50 年代勇士中锋，他三夺得分王，是早期 NBA 最稳定的内线得分手之一。",
 "connie hawkins": "“Hawk（鹰）”形容他腾空扣篮的锐利；“The Man”是纽约街头与 ABA 时代球迷对他统治力的直呼。他早年被误禁多年、后在 ABA 与 NBA 双双证明自己，是悲剧与天赋交织的传奇前锋。",
 "ed macauley": "“Easy Ed（轻松艾德）”形容他毫不费力般的丝滑球风；“Big Ed”为身形简称。作为 50 年代凯尔特人与圣路易斯鹰的中锋，他 1958 年夺冠、7 次全明星，后被交易换来了比尔·拉塞尔。",
 "george mcginnis": "“Big Mac（大麦克）”为姓氏趣味简称；“Baby Bull（牛犊）”形容他壮硕却灵动的身形；“The Hammer（铁锤）”则点出他暴力的低位。他是 70 年代 76 人与 ABA 步行者的双料全明星前锋。",
 "larry brown": "“Next Town Brown（下一城布朗）”调侃他执教足迹遍布几乎每一支球队；“Little General（小将军）”则因他身高不高却战术严谨、指挥若定。他是球员时代名宿、后来以教练身份拿下 2004 年活塞总冠军的名人堂教头。",
 "tony parker": "“T.P”为名字缩写；“Fiery Francophile（炽热法国迷）/ Parisian Torpedo（巴黎鱼雷）”点出他的法国血统与迅猛第一步。作为马刺法国籍控卫，他四夺总冠军、2007 年总决赛 MVP，与邓肯、吉诺比利组成 GDP 组合。",
 "david thompson": "“Skywalker（天行者）”形容他早於乔丹的飞天扣篮，是 70 年代最炫目的空中前锋之一；“D.T”为简称。效力丹佛掘金与超音速的他，曾在 1978 年单节狂揽 73 分。",
 "ralph sampson": "“Stick（竹竿）”源自他 2.24m 却瘦长的身形。作为 80 年代火箭状元中锋，他曾与奥拉朱旺组成“双塔”，新秀赛季即夺最佳新秀。",
 "bob lanier": "“Dobber / Bob-A-Dob”是童年亲昵叫法；“Moses（摩西）”则因他篮下如先知般指引球队。他是 70 年代活塞标志中锋，以巨大勾手与 8 次全明星闻名，生涯后期助雄鹿冲冠。",
 "earl monroe": "“The Pearl（珍珠）”源自他华丽如珍珠般圆润流畅的运球过人；“Black Jesus”是球迷对他球风神性的尊称；“The Magic Man（魔法师）”则点出其变幻莫测的进攻。他是 70 年代尼克斯与子弹的冠军后卫。",
 "elvin hayes": "“The Big E”为名字简称；“The Bionic Man（生化人）”形容他如机械般耐久的出场与得分；“The Big Enigma（大谜题）”则指他高产却低调的生涯。他 16 次全明星、1978 年率子弹夺冠，历史总得分高居前列。",
 "jason kidd": "“J-Kidd”为名字缩写与姓氏组合；“Ason Kidd”是他年轻时为耍酷故意去掉“J”的自封；“The Engine（引擎）”形容他驱动全队运转；“Mr. Triple Double（三双先生）”指其全面。两夺总冠军（2011 小牛），是历史助攻与抢断前列的控卫。",
 "dave debusschere": "“Big D”为简称；“Mr. Buffalo（布法罗先生）”点出他效力活塞前身（布法罗）的岁月。他是 60-70 年代活塞与尼克斯前锋、两夺总冠军，退役后还成为尼克斯总经理，是球员兼高管的典范。",
 "dennis rodman": "“The Worm（蚯蚓）”源自他少年时期扭动身体抢篮板的样子，被教练叫“worm”；“Dennis the Menace（捣蛋鬼丹尼斯）”形容他场外叛逆；“Rodzilla / El Loco（那个疯子，西语）”则点出他夸张的个性。5 夺总冠军、2 届篮板王，以多色头发与防守著称。",
 "gary payton": "“The Glove（手套）”源自他如手套般紧贴、锁死对手的防守，1996 年当选最佳防守球员；“GP”为姓名缩写。他是 90 年代超音速传奇控卫、2006 年随热火夺冠。",
 "kevin mchale": "“Black Hole（黑洞）”形容他在低位背身单打时把防守人“吸”进去的压迫感；“Herman Munster（赫尔曼·蒙斯特）”则因长相神似经典剧集角色。作为凯尔特人三巨头之一，他三夺总冠军，是历史最华丽大前之一。",
 "clyde drexler": "“Clyde the Glide（滑翔的克莱德）”源自他如滑翔机般流畅优雅的空中步伐（名字 Clyde 也呼应 70 年代电影《Shampoo》的风流发型师）。他是开拓者与火箭的飞天后卫，1995 年随火箭夺冠、10 次全明星。",
 "patrick ewing": "“Big Pat”为简称；“Hoya Destroya（霍亚毁灭者）”来自他母校乔治城大学 Hoya 队名；“The Big Fella / Beast”形容其禁区强悍。作为尼克斯队史中锋，他 11 次全明星却终生无冠，是“无冠伟大”的代表。",
 "ray allen": "“Ray-Ray”为昵称；“Sugar Ray（糖 Ray）”借拳王 Sugar Ray Leonard 的梗；“Jesus Shuttlesworth”取自斯派克·李电影《He Got Game》中由雷·阿伦饰演的角色名；“Gentleman（绅士）”形容其优雅。两夺总冠军，并曾长期保持历史三分王。",
 "sam jones": "“Mr. Clutch（关键先生）”形容他无数次在比赛尾声一剑封喉；“The Shooter（射手）”则是其本色。作为凯尔特人 60 年代王朝后卫，他手握 10 枚总冠军戒指，是史上夺冠最多的球员之一。",
 "carmelo anthony": "“Melo”为名字简称；“Hoodie Melo / Sweet Melon / Mel”多为变体。作为掘金与尼克斯时期的招牌进攻万花筒，他 10 次全明星、2013 年得分王，是历史总得分前列的得分手（生涯后期辗转多队无冠）。",
 "dominique wilkins": "“Nique”为名字简称；“The Human Highlight Film（人类精华影片）”形容他如录像集锦般炸裂的扣篮；“Nique-a-Zoid / Zoid”是球迷派生。作为老鹰队史传奇，他 9 次全明星、两夺扣篮大赛冠军，与乔丹的 1988 扣篮对决成经典。",
 "kyrie irving": "“Uncle Drew（德鲁叔叔）”来自他主演的 Pepsi 系列广告——扮成佝偻老头却球技惊为天人的“德鲁叔叔”；“Ankletaker（断踝者）”形容他摧毁防守人脚踝的 crossover；“Kai”为简称。2016 年随骑士夺冠，以极致控球闻名。",
 "nate thurmond": "“Nate the Great（伟大的奈特）”致敬推理童书主角，形容他的大心脏；“Chairman of the Boards（篮板主席）”则点出他顶级的篮板能力。作为勇士/骑士防守中锋，他生涯曾拿下“四双”，是 70 年代内线铁闸。",
 "pete maravich": "“Pistol Pete（手枪皮特）”来自父亲普雷斯·马拉维奇——因他出手如拔枪般迅疾潇洒而起的绰号。作为 70 年代老鹰/爵士后卫，他是 NCAA 历史得分王（保持多年），以花式传球与投篮闻名，却终生无冠。",
 "warren jabali": "“Mad Dog（疯狗）”形容他场上不死不休的拼抢；“Batman（蝙蝠侠）”则是 ABA 时期队友对其全面统治的戏称。他是 ABA 黄金时代的顶级后卫/前锋，多次入选 ABA 全明星。",
 "freddie lewis": "“Fritz / Fred”为亲昵简称。他是 ABA 印第安纳步行者王朝的发动机后卫，多次随队夺冠，以冷静组织与关键球著称。",
 "glen rice": "“G Money / G”为名字简称与“到关键时刻就进钱（money）”的双关。作为 90 年代神射，他是 1995 年全明星 MVP、2000 年随湖人夺冠，以接球跳投闻名。",
 "joel embiid": "“The Process（过程）”直接来自 76 人长期的“Trust the Process”重建口号，恰好呼应他的队名与成长轨迹；“JoJo”是家人对他的昵称。他 2023 年拿下 MVP、2022 与 2023 年两夺得分王，是喀麦隆出生的现代中锋代表。",
 "luka doncic": "“The Matador（斗牛士）/ El Matador”形容他如斗牛士般从容戏耍防守；“Wonder Boy（神奇小子）/ Luka Magic（卢卡魔法）”源自他欧洲赛场便展现的魔术天赋；“Cool Hand（冷静之手）”则点出其关键时刻的沉着。2018 年最佳新秀、2024 年 MVP，已是独行侠绝对核心。",
 "pascal siakam": "“Spicy P”玩了“Sexy P（性感 P）”的谐音——因他名字 Pascal 缩写 P、打法火热而得名。作为喀麦隆出身的猛龙前锋，他 2019 年夺冠并当选最快进步球员，以从替补打起的逆袭故事闻名。",
 "reggie miller": "“Uncle Reg（雷吉叔叔）”是球迷对他如长辈般稳定输出三分、又爱“教育”对手的昵称；“The Knick Killer（尼克斯杀手）”源自他与纽约麦迪逊广场花园的宿敌恩怨（多次绝杀）；“Killa / Freddy”多为变体。他是步行者队史传奇、5 次全明星，生涯无冠却以三分冷血留名。",
 "victor wembanyama": "“Wemby”为姓氏简称；“The Extraterrestrial / Alien（异星人/外星人）”形容他 2.24m 配超长臂展、动作却像后卫般的“非人类”特质。2023 年状元、2023-24 赛季最佳新秀，被普遍视为马刺下一代基石。",
 "cedric maxwell": "“Cornbread（玉米饼）”源自他小时候最爱吃玉米饼的童年外号；“The Rubberband Man（橡皮筋人）”形容他柔韧的身躯与伸展。作为凯尔特人 80 年代前锋，他是 1981 年总决赛 MVP，以关键球与更衣室喜感闻名。",
 "derrick rose": "“D-Rose”为名字缩写与昵称；“Windy City Assassin（风城刺客）”点出他芝加哥（Windy City）出身与冷血突破；“Pooh”来自他童年圆润的模样（绰号“Pooh Jackson”）。2009 年最佳新秀、2011 年以 22 岁成为史上最年轻 MVP。",
 "jimmy butler": "“Jimmy G. Buckets（进球吉米）”形容他关键时刻一手包办得分（bucket 即篮球俚语中的进球）的硬汉本色；“Playoff Jimmy（季后赛吉米）”则概括他一到季后赛就升级的传说。他 6 次全明星、2023 年率热火闯入总决赛。",
 "randy smith": "“Iron Man（铁人）”来自他惊人的耐久——曾连续出战 906 场常规赛（历史最长连续出场纪录之一）。作为 70 年代勇敢者/水牛城后卫，他是 2 届全明星与 1978 年全明星 MVP。",
 "tom chambers": "“T.C / Tommy Gun（汤米枪）”为名字简称与枪支梗；“Ken”为昵称。他是 80 年代得分型大前/中锋，太阳与超音速时期的稳定 20+ 分机器。",
 "jamaal wilkes": "“Silk（丝绸）”形容他丝滑流畅的进攻手感。作为湖人（3 冠）与勇士（1 冠）前锋，他是 70-80 年代“Showtime”前夜最优雅的锋线得分手之一，4 枚戒指在手。",
 "bobby jones": "“The Secretary of Defense（国防部长）”是他最著名的标签，形容他历史级的防守专注与扫荡能力。作为 80 年代 76 人前锋，他 1983 年夺冠、8 次入选最佳防守阵容，是赢球型角色球员典范。",
 "tom heinsohn": "“Tommy / Gunner（枪手）”为昵称；“Ack-Ack”源自他招牌的跳投出手声；“The Hawk / Dr. Hawkenstein”多为队友对其强硬风格的打趣。作为凯尔特人 60 年代前锋，他 8 夺总冠军，退役后又以教练身份再夺 2 冠。",
 "bob dandridge": "“Bobby D”为简称；“Greyhound（灰狗）”形容他灵快的推进；“Pick”为战术昵称。作为 70 年代雄鹿（1971 冠）与子弹（1978 冠）的双冠前锋，他两度夺冠、4 次全明星。",
 "charlie scott": "“Great Scott（好样的斯科特）”为名字双关昵称；“Scotty”为简称。作为北卡出身、ABA/NBA 双栖的后卫，他是 1976 年随凯尔特人夺冠的得分手。",
 "dwight howard": "“Superman（超人）”源自他 2008 年全明星扣篮大赛披红蓝披风飞天扣篮的经典造型；“D12”对应他身披的 12 号球衣。他是 2000 年代后期最强中锋（3 次 DPOY、5 次全明星），2020 年随湖人圆梦夺冠。",
 "jack sikma": "“Goldilocks（金发姑娘）”来自他一头金发；“Banger（硬撞）”形容他扎实的低位。作为 70-80 年代超音速中锋，他 1979 年夺冠，并以“Sikma move（后转身跳投）”成为技术流中锋样本。",
 "maurice cheeks": "“Mo / Little Mo”为名字昵称。作为 80 年代 76 人控卫，他是 1983 年总冠军成员与顶级外线锁防者，退役后成为知名助教与教练。",
 "pau gasol": "“Meal Ticket（饭票）”玩了“real deal（真货）”的谐音，也喻他为球队的“主菜”；“ET（外星人）”因长相神似电影角色；“Kung Pow（功夫）”则点出他西班牙式的柔和手感。两夺总冠军（湖人 2009、2010），是国际内线标杆。",
 "bob davies": "“The Harrisburg Houdini（哈里斯堡的胡迪尼）”源自他宾州老家，形容其如魔术师般的背后传球；“Li'l Abner”则为漫画梗昵称。作为 40-50 年代罗切斯特/圣路易斯鹰后卫，他是早期 NBA 最华丽的控卫之一。",
 "bobby wanzer": "“Hooks（钩手）”来自他招牌勾射；“Cover Boy（封面男）”则因英俊长相常登杂志。作为 50 年代罗切斯特皇家后卫，他是 1951 年总冠军成员与 6 届全明星。",
 "carl braun": "“Junior / Baby Face（娃娃脸）”形容他年轻清秀的长相。作为 50 年代尼克斯后卫/前锋，他是队史早期的得分核心与 5 届全明星。",
 "chet walker": "“The Jet（喷射机）”形容他飞快的第一步；“Checkmate / Peoria Pats / Gunsmoke”多为家乡（伊利诺伊 Peoria）或电影梗昵称。作为 60-70 年代前锋，他是 1967 年 76 人总冠军成员。",
 "chris bosh": "“CB4”为他身披的 4 号球衣代号；“The Boshtrich（鸵鸟·博什）”是 Bosh 与 ostrich 的拼合玩笑；“King of the Dragons（龙王）”呼应他热火时期与“龙”相关周边。作为热火三巨头之一，他两夺总冠军、11 次全明星。",
 "cliff hagan": "“Li'l Abner”借经典漫画乡巴佬角色的梗，调侃他质朴强悍的球风。作为 50-60 年代鹰队前锋，他是 1958 年总冠军成员与 6 届全明星。",
 "clyde lovellette": "“Jellybelly（果冻肚）”调侃他微凸的身形；“Boomer / Boom-Boom / The Whale（鲸鱼）/ Great White Whale（大白鲸）”多形容其庞大身板与暴力内线。作为 50 年代湖人/凯尔特人中锋，他多次夺冠。",
 "dick barnett": "“Skull（骷髅）”来自他光头长相；“Fall Back Baby（退后宝贝）”为其招牌后仰跳投的戏称。作为 60-70 年代尼克斯后卫，他是 1970、1973 两冠成员。",
 "gail goodrich": "“Stumpy（树桩）/ The Stump（桩子）”调侃他偏短的腿型；“Stump”也呼应他矮壮结实的身形。作为 70 年代湖人后卫，他是 1972 年总冠军成员与 5 届全明星（口罩射手）。",
 "jim pollard": "“The Kangaroo Kid（袋鼠小子）”形容他惊人的弹跳；“Bones（骨头）”则点出他清瘦的身形。作为 50 年代明尼阿波利斯湖人中锋/前锋，他随队拿下多枚冠军戒指。",
 "larry costello": "“Costy”为姓氏昵称。作为 60 年代 76 人与雄鹿后卫/教练，他是 6 届全明星，并作为教练率领雄鹿拿下 1971 年总冠军。",
 "louie dampier": "“Lou / Little Louie / King Louie”为昵称变体。他是 ABA 肯塔基上校队的传奇控卫，以精准远投成为 ABA 历史得分王级别的人物。",
 "manu ginobili": "“Gino”为名字简称；“El Contusione（瘀伤先生）”形容他不顾身体、屡屡摔得一身伤的拼法；“Manudona（马拉多纳·马努）”把他比作阿根廷球王；“Obi-Wan Ginobili”则是星战梗。作为马刺阿根廷分卫，他四夺总冠军、是“妖刀”代名词。",
 "maurice stokes": "“Mo / The Stoker（司炉工）/ The Cat（猫）/ The Magnificent（宏伟）”多为队友对其灵动与全面的戏称。作为 50 年代皇家队前锋，他是三双级巨星，却因训练中重伤早逝，留下悲情传奇。",
 "michael cooper": "“Coop”是姓氏 Cooper 的简称；作为湖人 Showtime 时代的防守大闸，他五夺总冠军却从未入选全明星，是著名的“赢球型角色球员”，1987 年当选最佳防守球员。",
 "paul westphal": "“Westy”为姓氏昵称。作为 70 年代太阳/凯尔特人/超音速后卫，他是 5 届全明星与 3 次总冠军成员（球员+后来的教练生涯皆辉煌）。",
 "roger brown": "“The Rajah（ Raja/酋长）”为昵称；“The Man With a Thousand Moves（千招先生）”形容他变化无穷的进攻。作为 ABA/NBA 步行者前锋，他三夺 ABA 总冠军，是印第安纳篮球符号。",
 "slater martin": "“Dugie”为童年昵称。作为 50 年代明尼阿波利斯湖人与凯尔特人后卫，他手握 5 枚总冠军戒指，是早期 NBA 小个控卫的赢家。",
 "tom gola": "“Mr. All-Around（全能先生）”概括他攻防一体；“Saint Gola / Ostrich（鸵鸟）”多为队友打趣；“Tommy”为昵称。作为 50-60 年代前锋，他率 La Salle 夺 NCAA 后于 NBA 再夺冠。",
 "tom sanders": "“Satch”为童年昵称。作为 60-70 年代凯尔特人前锋，他是 8 夺总冠军的“赢球型”角色球员，以防守与更衣室稳定著称。",
 "vern mikkelsen": "“The Great Dane / The Durable Dane（伟大的丹麦人/耐久的丹麦人）”源自他丹麦血统与强韧耐久。作为 50 年代明尼阿波利斯湖人前锋，他 4 夺总冠军，是早期 NBA 最全面的内线之一。",
 "walt bellamy": "“Bells / Mister Bellamy”为昵称。作为 60 年代中锋，他生涯场均 20+10、1993 年入名人堂，却因辗转多队而少被冠以鲜明外号。",
 "wayne embry": "“Goose”为昵称；“The Wall（墙）”形容他篮下如墙般的屏障。作为 60 年代中锋，他是首位非裔NBA总经理，球员时代多次全明星。",
 "zelmo beaty": "“Big Z / Z”为简称；“The Franchise（ franchise/招牌）”点出他的核心地位；“Mr. Clean（干净先生）”因光头而得；“Slim”则为身形。他 1971 年随犹他之星夺 ABA 总冠军，亦在 NBA 多次全明星。",
 "bernard king": "“The King（国王）”为名字 Bernard 的尊称（此处 DB 仅记“B”为缩写变体）；尼克斯时期他以招牌转身跳投被誉为得分机器，是 80 年代最致命的得分手之一。",
 "chris webber": "“C-Webb”为名字缩写与昵称；国王队“普林斯顿进攻”的核心，以华丽传球与面框进攻闻名。他是 5 届全明星、1993 年最佳新秀，却终生无冠。",
 "dikembe mutombo": "“Mt. Mutombo（穆托姆博山）”形容他遮天蔽日的封盖；“Deke”为昵称。四届最佳防守球员，他著名的赛后“摇手指”成为个人标志，并以慈善（刚果医院）留名。",
 "don nelson": "“Nellie”为名字 Don 的昵称。作为 60 年代凯尔特人 5 冠角色球员，他后来成为 NBA 历史胜场最多的教练之一（雄鹿/勇士/小牛等），以“小个阵容”创新闻名。",
 "earl lloyd": "“Big Cat（大猫）/ Cat”形容他敏捷；“The Squirrel（松鼠）”等为其灵动昵称；“Moon Fixer”则是队友玩笑。他是 1950 年首批登陆 NBA 的黑人球员之一，1955 年随锡拉丘兹夺冠。",
 "frank ramsey": "“The Kentucky Colonel（肯塔基上校）”源自他母校肯塔基大学与南方绅士气质。作为 50-60 年代凯尔特人，他是“超级第六人”鼻祖、7 夺总冠军。",
 "grant hill": "“G-Money”为名字缩写与“关键先生”双关；“Mr. Nice（好人先生）”形容其儒雅形象。作为 90 年代活塞/魔术前锋，他 7 次全明星、生涯后期 2018 年随骑士圆梦夺冠。",
 "jerry sloan": "“Spider（蜘蛛）”来自他长臂覆盖；“The Original Bull（初代公牛）”因他是芝加哥公牛队史首位巨星；“Charley Hustle（拼命查理）”则点出硬汉作风。球员时代后成为爵士传奇教练（铁血防守体系）。",
 "joe fulks": "“Jumpin' Joe（跳跃乔）”形容他 pioneering 的跳投；“The Kuttawa Clipper（卡图瓦快船）”源自他肯塔基老家 Kuttawa。作为 40-50 年代勇士前锋，他是早期 NBA 得分王与跳投革命先驱。",
 "john thompson": "“Big John（大约翰）”为尊称。作为乔治城大学名帅，他培养了尤因等内线，1984 年率队夺 NCAA 冠军，是 NCAA 最具影响力的非裔教练之一。",
 "lou hudson": "“Sweet Lou / Super Lou（甜路易/超人路易）”形容他丝滑的得分手感。作为 70 年代老鹰与开拓者后卫，他是 6 届全明星与稳定的 20+ 分得分手。",
 "pat riley": "“Riles”为姓氏昵称；“MacGyver（麦盖佛）”调侃他临场变通的执教智慧。作为 Showtime 湖人、尼克斯与热火的教头，他 5 夺总冠军，并发明了“three-peat（三连冠）”一词。",
 "phil jackson": "“Action Jackson（行动杰克逊）”是他球员时代的昵称；“The Zen Master（禅大师）”则因他将禅宗与心理学引入执教而由媒体加冕；“Bones（骨头）”形容其清瘦。作为球员 2 冠、教练 11 冠的史上最成功教头之一。",
 "sidney moncrief": "“Sid / Sir Sid / El Sid”为昵称变体；“The Squid（鱿鱼）”形容他长臂覆盖的防守。作为 80 年代雄鹿后卫，他是 2 届最佳防守球员与 5 届全明星。",
 "toni kukoc": "“Croatian Sensation（克罗地亚 sensations）/ Euro-Magic（欧魔）”点出他的克罗地亚出身与魔术般传球；“The Waiter（侍者，源自他招牌的背后假传真假动作）”“Kuki / The Pink Panther（粉红豹）/ Alien”多为变体。作为公牛 90 年代三连冠的“第三人”，他是欧洲前锋登陆 NBA 的先驱。",
 "tracy mcgrady": "“T-Mac”为名字缩写；“The Big Sleep（大 Sleep）”则形容他场上慵懒却致命的气质。2004 年“麦迪时刻”35 秒 13 分成为绝杀经典，7 次全明星却终生无冠。",
 "vince carter": "“Vinsanity（文斯狂热）”是他 1999-2000 新秀赛季引爆全联盟的疯狂扣篮表演的代称；“Air Canada（加拿大飞人）”因他是多伦多猛龙队的飞天前锋；“Half-Man Half-Amazing（半人半神）”形容他半人半神的弹跳；“Yoda（尤达）”是生涯后期球迷对他老而弥辣的尊称。",
 "walter davis": "“Walt / Sweet D / Candyman（糖果人）/ Man with the Velvet Touch（天鹅绒之手）”皆形容他丝滑甜美的投篮手感；“Greyhound（灰狗）”则点出速度。作为 70-80 年代太阳得分后卫，他是 6 届全明星。",
 "calvin murphy": "“Pocket Rocket（袖珍火箭）”形容他矮小（约 1.75m）却快如火箭的突破；“Cal”为昵称。作为火箭后卫，他是 NBA 历史最矮的得分机器之一，以罚球神准与强硬著称。",
 "chris mullin": "“Mully”为昵称。作为 80-90 年代勇士“跑轰”核心与“梦一队”成员，他是 5 届全明星，以一手精准的左撇子跳投闻名。",
 "dick mcguire": "“Tricky Dick / Slick Dick（狡猾迪克）”形容他鬼魅的传球与控球；“Dick the Knick”点出他尼克斯身份。作为 50 年代纽约控卫，他是 6 届全明星与球队大脑。",
 "doug collins": "“Play-a-Day”为其生涯绰号（形容其出勤与投入）。作为 70 年代 76 人后卫，他是 4 届全明星，退役后成为知名教练与解说。",
 "guy rodgers": "“Flip / Shake Hips（扭胯）”形容他花哨的运球与髋部晃动。作为 60 年代控卫，他是 1967 年 76 人总冠军成员与助攻大师。",
 "harry gallatin": "“The Horse（马）/ Farmer（农夫）”源自他伊利诺伊农家出身与吃苦耐劳的球风。作为 50 年代尼克斯前锋/中锋，他是全明星级篮板手与 1954 年全明星 MVP。",
 "jack twyman": "“Twy / Twacky / Smokey”为昵称变体。作为 60 年代皇家队前锋，他是 6 届全明星，并以长年照料瘫痪队友莫里斯·斯托克斯的义举而为人铭记。",
 "nat clifton": "“Sweetwater（甜水）”源自他年少时爱喝甜苏打水而得的外号；“Sweets”为简称。他是 1950 年首批登陆 NBA 的黑人球员先驱之一，50 年代尼克斯全明星。",
 "anthony davis": "“The Brow（浓眉）”直接来自他标志性的粗眉；“AD”则是名字缩写，现多作为其通用简称。作为鹈鹕与湖人中锋，他 2020 年随湖人夺冠并多次入选最佳防守阵容，是现代空间型内线的代表。",
 "demar derozan": "“Deebo”取自电影《Friday》中凶悍的角色 Deebo，形容他强硬的中距离单打风格；“Derozan”为名字变体。作为猛龙/马刺/国王得分后卫，他是四届全明星与稳定的 20+ 分机器。",
 "paul george": "“PG-13”既对应他姓名缩写 PG 与球衣号码 13，也暗合同名电影分级——暗示他“适合全家观看却暗藏锋芒”。作为步行者与快船前锋，他多次全明星、2016 年断腿后王者归来。",
 "marc gasol": "“La Tanqueta（小坦克，西语）”形容他扎实厚重的身板；“Big Marc / Big Spain / Big Burrito”多为身形与国籍（西班牙）梗。作为灰熊中锋，他 2013 年最佳防守球员、2019 年随猛龙夺冠。",
 "tim hardaway": "（见上）",
 "klay thompson": "“Splash（水花）”与兄弟 Stephen 并称“Splash Brothers（水花兄弟）”，形容二人三分如入水花般清爽致命；“Game 6 Klay”源自 2016 总决赛 G6 单场 11 记三分的爆炸夜；“Big Smokey / Killa Klay / The Electrician / Sea Captain”多为变体。他四夺总冠军。",
 "rasheed wallace": "（见上）",
 "karl-anthony towns": "“KAT”为名字缩写；“Special K”为变体；“Bodega K.A.T”玩了纽约 bodega（杂货铺）梗，呼应他在纽约长岛的成长。作为森林狼中锋，他以罕见精准的外线投射 redefine 了现代内线。",
 "yao ming": "“The Great Wall（长城）”源自他 2.29m 的庞大身形与中国背景；“The Dynasty（王朝）”则呼应火箭被中国资本入股、以及他在休斯敦作为票房基石的地位；球迷也常昵称他“大姚（Big Yao）”。作为 NBA 首位国际状元中锋，他 8 次全明星、架起中美篮球桥梁。",
 "richard hamilton": "“Rip”为名字 Richard 的简称；“The Man in the Mask（面具人）”源自他因鼻梁伤长期佩戴防护面具；“Hollywood”则形容他招牌的“Hollywood finish（后仰挑篮）”。作为 2004 年活塞夺冠的得分后卫，他以无球跑动闻名。",
 "sam cassell": "（见上）",
 "richie guerin": "“The Leatherneck（皮颈者）”源自他海军陆战队（Leatherneck 是陆战队员的俗称）服役背景，形容其硬汉作风。作为 50-60 年代尼克斯后卫，他是 6 届全明星与队史早期得分核心。",
 "rudy tomjanovich": "“Rudy T”为名字简称。作为球员他是 70 年代火箭前锋（两夺全明星），更作为教练率领火箭拿下 1994、1995 两连冠，“屡受伤却坚韧”是他球员时代的标签。",
 "bob houbregs": "“Houby / Bobby / Tubes（管筒，形容其高瘦身形）”为昵称变体。作为 50 年代超音速/湖人中锋，他是西雅图早期篮球符号与 1953 年得分王。",
 "brian taylor": "“BT”为姓名缩写。作为 ABA/NBA 后卫（篮网/ 超音速等），他以速度著称，并是 ABA 扣篮大赛早期参与者。",
 "chuck cooper": "“CC”为姓名缩写。作为 1950 年首批登陆 NBA 的黑人球员之一（凯尔特人），他与拉塞尔同入名人堂，是拓荒先驱。",
 "drazen petrovic": "“Petro”为姓氏简称；“Mozart of the Hoops（篮圈莫扎特）”形容他如音乐般精准优雅的外线投射。作为克罗地亚后卫，他是欧洲球员登陆 NBA 的先驱，可惜 1993 年因车祸早逝。",
 "rod thorn": "“Hots”为其球员时代昵称（形容其火热手感）。他更以长期 NBA 高管/球探身份闻名（曾主导多笔传奇交易）。",
 "slick leonard": "“Bobby”为其本名昵称；“Slick（滑头）”形容他球员时代狡猾的球风。他后来成为 ABA/ NBA 名帅（步行者），以温厚形象著称。",
 "bill melchionni": "“Billy / Mel / Cy / Clops / Cyclops（独眼，可能源于护目镜或长相）”为昵称变体。作为 70 年代 76 人与 ABA 篮网后卫，他是球队早期的进攻发动机。",
 "woody sauldsberry": "“Sauldy”为姓氏昵称；“Sling Shot / Longshot Woody（远投伍迪）”形容其投篮射程。作为 60 年代勇士中锋，他是 1958 年最佳新秀。",
 "bill bridges": "“The Train（火车）”形容他如列车般持续推进的强硬；“Big Bill”为身形简称。作为 60-70 年代老鹰/勇士前锋，他是篮板型角色球员与多次全明星。",
 "brook lopez": "“Splash Mountain（水花山）”玩了“Splash（水花兄弟梗）+ 庞大身形”的双关；“Bropez”为昵称。作为篮网/雄鹿中锋，他以能投三分的长人外线火力与护框闻名。",
 "chet holmgren": "“Cheddar（奶酪）”为名字 Chet 的谐音昵称。作为雷霆现代空间型中锋，他 2023 年榜眼、以盖帽与投射成为新一代内线样本。",
 "deandre jordan": "“DeAndre 3000”玩了嘻哈歌手 OutKast 的“Andre 3000”梗，形容其不止于扣篮的多面身手。作为快船/篮网中锋，他是 2015 年全明星与多次篮板王。",
 "don buse": "“Boo”为名字简称。作为 70-80 年代后卫（步行者/ 太阳等），他是 ABA 时代顶尖的防守型控卫与抢断专家。",
 "draymond green": "“Day-Day”与“Dray”都是名字 Draymond 的亲昵变体，源于家人从小到大的称呼。作为勇士“死亡五小”发动机，他 4 夺总冠军、2017 年最佳防守球员，以激情与全能著称。",
 "horace grant": "“The General（将军）”形容他指挥防守的沉稳；“The Enforcer（执法者）”则点出他硬朗的低位与补防。作为公牛 1991-93 三连冠与魔术 1995 总决赛的内线，他是“公牛王朝”蓝领核心。",
 "jalen williams": "“J-Dub”为名字 Jalen 与 William 的组合简称。作为雷霆侧翼，他是 2024 年最佳新秀、并以全面防守与进攻成为俄城新一代核心之一。",
 "jrue holiday": "“JHolla / The Jruth（真理，玩 truth 谐音）/ Kung fu Jrue（功夫朱）”多为变体昵称。作为全明星后卫，他 2021 年随雄鹿夺冠、2024 年随凯尔特人再夺冠，以防守著称。",
 "larry kenon": "“K / Special K / Dr. K / Mr. K / Big Cat / Super K”多为昵称变体（Special K 玩麦片梗）。作为 70 年代 76 人与 ABA 步行者前锋，他是 1977 年 ABA 冠军成员。",
 "lionel hollins": "“L-Train（L 火车）”形容他稳健推进的节奏。作为 70-80 年代超音速后卫，他是 1979 年总冠军成员与球队大脑，退役后成为教练。",
 "maurice lucas": "“Luke / Mo”为昵称；“The Enforcer（执法者）”形容他硬朗的低位与更衣室领袖力。作为 1977 年开拓者夺冠的核心大前，他是“撕裂之城”早期图腾。",
 "paul silas": "“Papa Bear（熊爸）”形容他如家长般稳重的更衣室地位；“Shotgun（猎枪）”则是其投篮昵称。作为 70 年代凯尔特人/太阳前锋，他两夺总冠军与多次篮板王。",
 "rajon rondo": "“Johnny / Swag”为昵称；“Playoff Rondo（季后赛隆多）”概括他常规赛平平、一到季后赛就升级的传说。作为凯尔特人 2008 年夺冠的控卫，他以高篮球智商与传球闻名。",
 "scott wedman": "“Scotty”为简称。作为 70-80 年代骑士/超音速前锋，他是可靠的角色得分手，并曾随超音速两度闯入总决赛。",
 "ted mcclain": "“Hound Dog（猎犬）”形容他如猎犬般紧追的防守。作为 70 年代尼克斯后卫，他是坚韧的防守型角色球员。",
 "tom thacker": "“Tack / Cobra（眼镜蛇）/ Mr. Clutch / Thack”多为昵称变体。作为 60 年代辛辛那提皇家与凯尔特人后卫，他是 1968 年总冠军成员。",
 "tyson chandler": "“TC”为姓名简称。作为防守型中锋，他是 2011 年小牛夺冠的禁区屏障、2012 年最佳防守阵容，并以“空接之城”的终结闻名。",
 "b.j. armstrong": "“The Kid（小子）”为其生涯早期的昵称。作为公牛 90 年代三连冠（1991-93）的替补控卫，他是冠军阵容里的稳定火力点。",
 "bill cartwright": "“Mr. Bill / Teach / Dollar Bill / Medical Bill（医疗比尔，因频繁伤停）/ Billy Idle / Invisi-Bill”多为昵称变体。作为公牛 90 年代三连冠的中锋，他是内线蓝领支柱。",
 "bill laimbeer": "“Lambs / Lamb / Freddie / The Prince of Darkness（暗黑王子）/ His Heinous / Counterfeit Bill / The Incredible Hulk（绿巨人）”多为队友对其凶悍球风的戏称。作为活塞“坏小子军团”中锋，他两夺总冠军（1989、1990）。",
 "billy paultz": "“The Whopper（华堡，汉堡王巨无霸）”调侃他壮硕身形；“Baby Huey（小休伊）”则为漫画梗。作为 ABA/NBA 中锋，他是 70 年代篮网与马刺的低位核心。",
 "bob boozer": "“Bullet Bob（子弹鲍勃）/ Big Bob / Booze / Coot”多为昵称变体。作为 60-70 年代公牛/雄鹿前锋，他是 1971 年雄鹿总冠军成员与稳定得分手。",
 "bob harrison": "“Tiger（老虎）”为昵称。作为 50-60 年代湖人/活塞后卫，他是早期 NBA 的快攻型得分手。",
 "bob netolicky": "“Neto”为昵称。作为 ABA 印第安纳步行者前锋，他是球队三夺 ABA 总冠军时代的内线支柱。",
 "caron butler": "“Tuff Juice（硬果汁）”源自他绰号背后的“强硬”精神（他自述童年被叫 Tuff Juice）。作为奇才/小牛等前锋，他是 2004 年全明星与 2011 年随小牛夺冠。",
 "cazzie russell": "“Jazzy / Snazzy（潇洒）”形容他优雅的球风。作为 60-70 年代后卫（活塞/ 尼克斯等），他是 1970 年总冠军成员与 7 届全明星。",
 "danny green": "“Icy-Hot（冰火）”形容他手感起伏（icy 冰凉/ hot 火热）的调侃。作为马刺/猛龙/湖人后卫，他是 3D 样本、2019 年随猛龙夺冠、2020 年随湖人再夺冠。",
 "dave twardzik": "“Pinball（弹珠）”形容他如弹珠机般在人群中穿梭的灵巧。作为 70 年代开拓者后卫，他是 1977 年夺冠阵容的控卫。",
 "david west": "“The 17-Foot Assassin（17尺刺客）”形容他招牌的长两分跳投与冷血终结。作为黄蜂/步行者大前与马刺 2017、2018 两冠角色球员，他是技术流内线的样本。",
 "derrick white": "“The Buffalo（水牛）”源自他母校科罗拉多大学水牛队（Buffaloes）。作为凯尔特人后卫，他 2024 年随队夺冠，以防守与季后赛关键球著称。",
 "don chaney": "“Duck（鸭子）”为昵称。作为凯尔特人 70 年代后卫，他是两夺总冠军（1974、1976）的角色球员，退役后也执教多年。",
 "donnie freeman": "“Don / Free”为昵称。作为 ABA 印第安纳步行者后卫，他是球队早期的得分发动机与多次全明星。",
 "flynn robinson": "“Electric Eye（电眼）/ Instant Point（即插点）/ Bobbie”多为昵称变体。作为 70 年代湖人/子弹后卫，他是 1972 年总冠军成员与得分手。",
 "fred brown": "“Downtown Freddie（ downtown 弗雷迪，指远投）”形容他的三分射程；“Freddie”为昵称。作为 70-80 年代超音速后卫，他是 1979 年总冠军成员。",
 "fred vanvleet": "“FV / Steady Freddy（稳健弗雷迪）”形容他稳定可靠的控场。作为落选秀逆袭样本，他 2019 年随猛龙夺冠，后成为火箭核心控卫。",
 "george johnson": "“Fly Swatter（灭蝇拍）”调侃他遮天蔽日的封盖。作为 70-80 年代马刺/ 爵士中锋，他是 1978 年 ABA 冠军成员与盖帽专家。",
 "glen combs": "“The Kentucky Rifle（肯塔基来复枪）”形容他精准的远投。作为 ABA 肯塔基上校后卫，他是球队得分火力点。",
 "glenn robinson": "“Big Dog（大狗）”为其著名外号；“The Chosen One（天选之子）”则是他选秀前的媒体加冕（1994 年状元）。作为雄鹿/步行者前锋，他是稳定的 20+ 分得分手。",
 "jack coleman": "“Old Rancher（老牧场主）/ Kentucky Colonel（肯塔基上校）/ Blackjack（黑杰克）”多为昵称变体。作为 50 年代罗切斯特皇家前锋，他是 1951 年总冠军成员。",
 "jamal murray": "“Blue Arrow（蓝箭）”源自他加拿大国籍与迅猛突破（蓝=加拿大配色）；“Glitch（故障）”形容其难以预测的进攻；“Maple Curry（枫叶库里）”则点出加拿大出身与射手本色。作为掘金后卫，他 2023 年随队首夺总冠军。",
 "jeff mullins": "“Pork Chop（猪排）/ Mulls”为昵称。作为 70 年代勇士/老鹰后卫，他是 1975 年勇士爆冷夺冠的得分核心。",
 "jim brewer": "“Brew / Papa”为昵称。作为 70 年代湖人/骑士前锋，他是篮板型角色内线。",
 "jim cleamons": "“Jimmy”为昵称。作为 70 年代湖人/ 子弹后卫，他是冠军队的角色拼图，退役后成为名帅助教。",
 "jim eakins": "“Jimbo / Jumbo（巨兽）”形容其高大身形。作为 70 年代篮网/ 76 人中锋，他是 ABA/NBA 的低位替补。",
 "john johnson": "“J.J”为简称。作为 70-80 年代火箭/ 超音速前锋，他是 1979 年超音速总冠军的得分主力。",
 "jon mcglocklin": "“Jonny Mac / Moose（驼鹿）/ The Original Buck（初代雄鹿）”为其昵称。作为密尔沃基雄鹿创始后卫，他是 1971 年总冠军成员与球队早期符号。",
 "juwan howard": "“Nook”为昵称（来源说法不一，多为队友玩笑）。作为 90 年代 Michigan “Fab Five”出身的前锋，他生涯横跨多队，并随热火 2012、2013 两冠（球员+后续助教）。",
 "kevin willis": "“Devo / Fresh / T-Rex（雷克斯，恐龙梗）/ Big Smoothie / Motown”多为昵称变体。作为 80-2000 年代长青前锋，他效力 20+ 赛季、曾随 2003 年马刺夺冠。",
 "khris middleton": "“Khash Money（卡什钱）/ WD-40（万能油，形容其润滑般稳定）/ Baby Joe Johnson”多为变体。作为雄鹿前锋，他是 2021 年总冠军成员与多次全明星，以关键球著称。",
 "kyle lowry": "“Mr. Raptor（猛龙先生）/ KLow / G.R.O.A.T（Greatest Raptor of All Time 缩写）/ North Philly's Finest（北费城之光）/ Bulldog（牛头犬）”多为变体。作为猛龙控卫，他 2019 年率队首夺总冠军并当选全明星 MVP。",
 "luguentz dort": "“Lu / Dortress（铁闸，Dort + fortress）/ Dorture Chamber（刑罚室，Dort + torture）”多玩他姓氏与窒息防守的双关。作为雷霆防守型侧翼，他以锁死对手箭头闻名。",
 "luke jackson": "“Big Jack / Luscious Lucious（甜腻卢休）/ Big Luke / Batman”多为昵称变体。作为 60-70 年代皇家/ 76 人前锋，他是 1967 年总冠军成员。",
 "m.l. carr": "“Lunchbox（饭盒）”调侃他勤恳如蓝领的球风。作为 70-80 年代凯尔特人前锋，他是 1981、1984、1986 三冠成员与球队能量源。",
 "mark aguirre": "“Ziggy / The Pillsbury Doughboy（皮尔斯伯里面团宝宝）/ Elephant Drawers（象裤）/ The Muffin Man（松饼人）/ Fat Daddy（胖爹）”多为队友对其壮硕身形的打趣。作为 80 年代活塞前锋，他是 1989、1990 两冠成员。",
 "mehmet okur": "“Memo / Money Man（钱人）”为昵称变体。作为土耳其空间型中锋，他是 2004 年活塞夺冠的板凳火力与关键三分点。",
 "merv jackson": "“The Magician（魔术师）”形容他鬼魅般的传球。作为 ABA 印第安纳步行者后卫，他是球队早期的进攻魔术师。",
 "michael finley": "“Fin Dawg（芬狗）”为昵称。作为 90-2000 年代独行侠/马刺后卫，他是 2007 年随马刺夺冠的老将得分手。",
 "mikal bridges": "“The Warden（看守）/ Noodles（面条）/ Inspector Go Go Gadget（巡查 Gadget 探长）/ String Bean（豆角）/ Brittle（脆）/ Praying Mantis（螳螂）/ Brooklyn Bridges”多为变体昵称。作为太阳/篮网侧翼，他以耐久出勤与防守著称。",
 "mike gale": "“Flipper（鳍）/ Philly Dog（费城狗）/ Sugar（糖）”多为昵称。作为 ABA/NBA 后卫（篮网/ 马刺等），他是 1974 年 ABA 冠军成员。",
 "mike miller": "“Skinny（瘦长）”形容其清瘦身形。作为神射后卫，他是 2006 年最佳第六人、并随 2012 热火与 2013 马刺夺冠。",
 "mike riordan": "“Bags / Iron Mike（铁麦克）”为昵称。作为 70 年代子弹前锋，他是 1978 年总冠军成员。",
 "norm nixon": "“Big / Stormin' Norman（风暴诺曼）/ The Storm（风暴）/ Savoir Faire（法式从容）/ Sav / Mr. May（五月先生，指季后赛）”多为变体。作为 80 年代湖人控卫，他是两夺总冠军（1980、1982）的发动机。",
 "norman powell": "“Norm / Stormin Norman”为昵称变体。作为得分后卫，他随 2019 猛龙夺冠，后以稳定火力辗转开拓者等队。",
 "p.j. brown": "“Big Cat（大猫）”为昵称。作为 90-2000 年代防守型大前/中锋，他随 2008 凯尔特人夺冠，以硬朗蓝领著称。",
 "paul seymour": "“The Iron Man（铁人）”形容其耐久与硬朗。作为 50 年代罗切斯特皇家后卫，他是 1951 年总冠军成员。",
 "quinn buckner": "“Q.B”为姓名缩写。作为 70-80 年代凯尔特人/雄鹿后卫，他是 1986 年总冠军成员与防守型控卫。",
 "rashard lewis": "“Sweet Lew（甜路易）/ The Blade（刀锋）/ Young Fella（小伙子）/ Quiet Man（沉默人）”多为变体。作为超音速/魔术前锋，他是 2008 年凯尔特人夺冠的板凳火力。",
 "red kerr": "“Johnny / Iron Man（铁人）/ Big Red（大红）”为昵称。作为 50-60 年代老鹰/子弹中锋，他是 1967 年 MVP 级内线，退役后成为著名解说。",
 "red rocha": "“The Thin Man（瘦长人）/ The Splendid Splinter（华美木片）”形容其清瘦身形。作为 50 年代湖人前锋，他是明尼阿波利斯湖人王朝成员。",
 "rich jones": "“House（房子）”为昵称。作为 70 年代 ABA/NBA 前锋，他是可靠的角色内线。",
 "rick mahorn": "“Ricky / McNasty（脏麦克）/ Leon（里昂）”多为昵称变体。作为活塞“坏小子”中锋，他是 1989 年总冠军成员，以强硬著称。",
 "ron boone": "“Instant Offense（即插进攻）/ The Legend（传奇）”形容其即插即用的得分。作为 ABA/NBA 后卫（星光/ 爵士等），他是 ABA 得分机器与耐久纪录保持者之一。",
 "scottie barnes": "“Scottie B”玩了他与名宿斯科蒂·皮蓬同名的梗（也被叫“Scottie Pippen 2.0”）。作为猛龙侧翼，他是 2021-22 最佳新秀，以全能身手著称。",
 "sean elliott": "“Ninja（忍者）/ Silly（呆）”为其昵称变体。作为马刺前锋，他是 1999 年总冠军成员，以关键球（”Memorial Day Miracle“）留名。",
 "serge ibaka": "“Air Congo（刚果飞人）/ Mafuzzy Chef（马富齐大厨，玩他本名 Mfuzzy 谐音）/ Iblaka（伊布拉卡）”多为变体。作为雷霆/猛龙中锋，他是 2019 年随猛龙夺冠的盖帽专家。",
 "shane battier": "“Batman（蝙蝠侠）/ Battle（战斗）”为昵称变体。作为火箭/热火前锋，他是 2006、2012、2013 两（三）冠的“赢球型 3D”样本，以智商防守闻名。",
 "sidney wicks": "“Super Sidney（超人西德尼）”为昵称，形容他 70 年代开拓者时期华丽的面框进攻；他是“撕裂之城”早期得分前锋。",
 "steve smith": "“Smitty”为昵称。作为 90 年代老鹰后卫，他是稳定的得分手与 2003 年随马刺夺冠的板凳火力。",
 "tayshaun prince": "“Tay”为简称；“Compton Kid（康普顿小子）”点出他的加州康普顿出身。作为活塞 2004 年夺冠的防守侧翼，他以罩住对手箭头闻名。",
 "tony allen": "“The Grindfather（研磨教父）”形容他硬朗的“研磨”式防守；“Trick or Treat Tony（不给糖就捣蛋托尼）”是万圣梗昵称；“Gucci（古驰）”则调侃其穿搭。作为灰熊/凯尔特人防守尖兵，他 2008 年随绿军夺冠。",
 "trooper washington": "“Tom”为昵称。作为 ABA 中锋，他是匹兹堡/纽约网队时期的篮板型内线。",
 "willie naulls": "“The Whale（鲸鱼）/ Sweetcakes（甜糕）”多为身形与昵称梗。作为 60 年代尼克斯/湖人前锋，他是全明星级得分手。",
 "bill calhoun": "“The Splinter（木片）”调侃他清瘦身形。作为 50 年代凯尔特人前锋，他是球队早期的轮换得分手。",
 "bill hosket": "“Hoss（大块）”为昵称。作为 60-70 年代尼克斯/骑士前锋，他是可靠的角色内线。",
 "bill keller": "“Billy / Mickey Rooney（米奇·鲁尼，借矮个子演员梗）”为昵称。作为 70 年代勇士后卫，他是板凳火力点。",
 "bill newton": "“Fig（无花果）”为昵称。作为 ABA 前锋，他是肯塔基/犹他之星的篮板型角色。",
 "billy kenville": "“The Kid（小子）/ Billy the Kid（比利小子）”为昵称（借西部枪手梗）。作为 60 年代锡拉丘兹前锋，他是球队轮换。",
 "billy thompson": "“B.T. Express / World”为昵称变体。作为 80 年代 76 人/热火前锋，他是板凳得分手。",
 "bison dele": "“Zobi”为昵称。作为中锋，他 1998 年随公牛夺冠，退役后不幸遇害，留下悲情传奇。",
 "bob arnzen": "“Arnie”为昵称。作为 60-70 年代皇家/骑士前锋，他是轮换角色球员。",
 "bob hansen": "“Bobby”为昵称。作为 80 年代爵士/老鹰后卫，他是可靠的板凳火力。",
 "bob love": "“Butterbean（扁豆）/ Bean（豆）”调侃他瘦长身形。作为 60-70 年代公牛前锋，他曾是球队得分核心与全明星。",
 "bob weiss": "“Bobby / Iron Man（铁人）”为昵称。作为 70 年代公牛/鹰后卫，他是耐久的板凳控卫。",
 "bobby portis": "“Bobby Buckets（进球波蒂斯）/ The Mayor of Milwaukee（密尔沃基市长）/ BP / Crazy Eyes（狂眼）/ Big Bob”多为变体。作为雄鹿/奇才大前，他以硬朗与激情闻名。",
 "boris diaw": "“Bobo / 3D / French Magician（法国魔术师）”多为变体。作为马刺前锋，他 2007 年随队夺冠，以传球视野与灵巧著称。",
 "brad holland": "“Potsie Weber（波茨·韦伯，借《欢乐时光》角色）”为昵称。作为 80 年代湖人/快船后卫，他是板凳得分手。",
 "brandon roy": "“B-Roy / Daggers（短剑，形容其终结）/ The Natural（天成）”多为变体。作为开拓者后卫，他是 2007 年最佳新秀，却因膝伤早逝般退场。",
 "brendan haywood": "“Baby Huey（小休伊，借卡通胖鸭梗）”调侃其壮硕身形。作为奇才/小牛中锋，他是轮换护框者。",
 "brent barry": "“Bones（骨头）”形容其清瘦身形。作为后卫，他是 1999、2005、2007 年三夺总冠军的神射手（其父为里克·巴里）。",
 "brian cardinal": "“The Custodian（保洁员）/ Citizen Pain（痛苦公民）/ The Janitor（门房）”多为更衣室/硬汉昵称。作为步行者/森林狼前锋，他是蓝领角色球员。",
 "brian scalabrine": "“White Mamba（白曼巴）/ Veal Scalabrine（小牛排斯卡）/ The Ginger Ninja（红发忍者）/ Scal”多为自嘲昵称。作为凯尔特人 2008 年夺冠的板凳老将，他因“最弱NBA球员”梗在网络走红。",
 "brian shaw": "“B. Shaw”为昵称。作为湖人 90 年代后卫，他是三连冠时期的板凳大脑，退役后成为助教。",
 "bruce brown": "“Cowboy Bruce（牛仔布鲁斯）/ Biggie Smalls”多为昵称。作为后卫/侧翼，他 2024 年随凯尔特人夺冠。",
 "byron scott": "“Lord Byron（拜伦勋爵）”玩诗人拜伦的谐音梗。作为湖人 80-90 年代后卫，他是“Showtime”与 80 年代末三连冠的成员。",
 "caldwell jones": "“Pops / C.J / The Doctor of Defense（防守博士）”多为变体。作为 70-80 年代 76 人/雄鹿中锋，他是盖帽与篮板型的防守内线。",
 "carl herrera": "“Amigo（老友，西语）”为昵称。作为火箭前锋，他是 1994、1995 两连冠的轮换内线。",
 "channing frye": "“Buffet of Goodness（美味自助）”为球迷戏称。作为空间型大前，他是 2007 年太阳与后来骑士的板凳投射点。",
 "charles dudley": "“Grasshopper（蚱蜢）/ Hopper（跳跃者）”形容其灵动的步伐。作为 70 年代勇士后卫，他是 1975 年夺冠的板凳组织者。",
 "charles johnson": "“Charlie / C.J / Jack（杰克）”为昵称变体。作为 70 年代勇士/子弹后卫，他是轮换角色。",
 "charles jones": "“C.J / Gadget（小机灵）”为昵称。作为 80 年代子弹/火箭前锋，他是防守蓝领。",
 "charles oakley": "“Oak Tree（橡树）/ Oak（橡）”形容其如橡树般稳固的篮板与前场肉搏。作为公牛/尼克斯大前，他是 90 年代最强硬汉蓝领之一。",
 "chris andersen": "“Birdman（鸟人）”源自他满身纹身与腾空封盖，以及后来与魔鬼鱼相关的形象。作为热火 2013 年夺冠的板凳活力内线，他以染发与能量闻名。",
 "chris boucher": "“Swatterboy（灭蝇男孩）/ Slimm Duck（瘦鸭）/ TreyBoucher / Block Quebecois（魁北克封盖者）”多为变体。作为猛龙/凯尔特人中锋，他 2019 年随猛龙夺冠。",
 "chris chiozza": "“Cheese（奶酪）”为昵称。作为控卫，他是马刺/奇才等队的板凳组织者。",
 "chris ford": "“The Mad Bomber（疯狂轰炸机）/ The Hot Dog（热狗）”形容其远投与表演欲。作为 80 年代凯尔特人后卫，他是 1981、1984、1985、1986 多冠的板凳火力。",
 "chris jent": "“Ivan Drago（伊万·Drago，借《洛奇》苏联拳手）”为昵称。作为 90 年代末火箭/尼克斯前锋，他是短命轮换。",
 "chuck nevitt": "“Chuck E. Cheese（查克·E·芝士，借儿童餐企梗）/ Human Victory Cigar（人类胜利雪茄）”多为身高（2.26m）与吉祥物梗。作为中锋，他生涯辗转多队、1985 年随湖人夺冠。",
 "chuck share": "“Charlie”为昵称。作为 50-60 年代老鹰/湖人中锋，他是 1958 年夺冠的轮换内线。",
 "chuck terry": "“Teen Angel（少年天使）/ Carlos”为昵称。作为 70 年代勇士/篮网后卫，他是板凳得分手。",
 "chucky brown": "“Wild Thing（狂野之物，借电影梗）”为昵称。作为前锋，他生涯辗转 12 队、1995 年随火箭夺冠，是著名的“流浪冠军”。",
 "clemon johnson": "“Clem”为昵称。作为 70-80 年代开拓者/活塞/凯尔特人中锋，他是 1977、1981、1984、1986 多冠的防守蓝领。",
 "cliff levingston": "“Good News（好消息）/ House（房子）”为昵称。作为 80-90 年代老鹰/公牛中锋，他是 1991、1992、1993 公牛三连冠的板凳内线。",
 "clifford ray": "“Cliff / The Mule（骡子）”形容其吃苦耐劳的篮板。作为 70 年代勇士/凯尔特人中锋，他是 1975、1980 等冠的防守内线。",
 "clifford robinson": "“Cliff / Uncle Cliffy（克利夫叔叔）”为昵称。作为开拓者大前，他是 90 年代“撕裂之城”的得分与防守核心、全明星。",
 "collin gillespie": "“Villain Jr.（小反派）”为昵称。作为控卫，他是掘金/76 人等队的年轻板凳。",
 "corey brewer": "“The Drunken Dribbler（醉运球手，自嘲）/ Greyhound（灰狗）”为昵称。作为侧翼，他 2011 年随小牛夺冠，以跑动与速度闻名。",
 "corliss williamson": "“Big Nasty（大脏）”调侃他强壮硬朗的球风。作为国王/活塞大前，他是 2002 年随湖人夺冠的板凳火力。",
 "d.j. mbenga": "“D.J / Congo Cash（刚果现金）”为昵称。作为刚果中锋，他 2009、2010 年随湖人两夺总冠军。",
 "dan majerle": "“Thunder Dan（雷霆丹）”形容他如雷霆般的外线远投。作为太阳后卫，他是 90 年代“跑轰”的防守型三分手与全明星。",
 "dan roundfield": "“Rounds（圆子，借本名 Round）/ Dr. Rounds（圆子博士）”为昵称。作为 80 年代老鹰中锋，他是全明星级篮板手。",
 "dan swartz": "“Dogpatch（狗镇）”为昵称。作为 60 年代凯尔特人前锋，他是 1964 年夺冠的轮换。",
 "darko milicic": "“The Human Victory Cigar（人类胜利雪茄）”同“吉祥物”梗（与内维特类似）。作为 2003 年榜眼，他 2004 年随活塞夺冠却生涯平庸，是选秀“水货”典型。",
 "darnell hillman": "“Dr. Dunk（扣篮博士）”形容其华丽扣篮。作为 70 年代开拓者/步行者前锋，他是 ABA/NBA 的表演型内线。",
 "darrell walker": "“Junkyard Dog（垃圾场狗）/ Sky（天空）/ Biggie”多为昵称。作为 80-90 年代子弹/活塞后卫，他是 1991、1992、1993 公牛三连冠的板凳防守者。",
 "darvin ham": "“Dunkin Darvin（扣篮达文）/ Ham Slamwich（火腿扣三明治）”为昵称。作为 90-2000 年代雄鹿/湖人前锋，他 2004 年随活塞夺冠，后成为名帅（2021 湖人总冠军教头）。",
 "dave gambee": "“Julius（尤利乌斯）”为昵称。作为 60 年代勇士/76 人前锋，他是 1967 年夺冠的轮换。",
 "dave stallworth": "“The Rave（狂热）”为昵称。作为 60-70 年代凯尔特人/勇士前锋，他是 1968、1969 等冠的板凳火力。",
 "david thirdkill": "“The Sheriff（警长）”为昵称。作为 80 年代太阳/凯尔特人前锋，他是 1986 年夺冠的短命轮换。",
 "deshawn stevenson": "“Papa Smurf（蓝精灵老爸）/ The Locksmith（锁匠）/ D-Steve”多为变体。作为奇才/小牛后卫，他 2011 年随小牛夺冠。",
 "dean meminger": "“The Dream（梦想）”为昵称（与“大梦”无关，纯本名梗）。作为 70 年代尼克斯后卫，他是 1970、1973 两冠板凳。",
 "dejounte murray": "“Baby Boy（宝贝男孩）”为昵称。作为马刺控卫，他是 2018 年随队夺冠的全明星级双能卫。",
 "dennis awtrey": "“Tree（树）/ Moose Breath（驼鹿息）/ Dennis the Menace（捣蛋鬼丹尼斯）/ Harpo”多为变体。作为 70 年代湖人/太阳中锋，他是 1972 年夺冠的防守内线。",
 "derek anderson": "“Smooth（丝滑）”形容其出手手感。作为 90-2000 年代后卫，他是 1997 年最佳新秀、开拓者得分手。",
 "derek fisher": "“D-Fish”为昵称。作为湖人 00 年代后卫，他是五夺总冠军的“0.4 秒”关键先生与球队大脑。",
 "derrick coleman": "“D.C / Joe Jackson / Coast”多为昵称。作为 90 年代新泽西篮网大前，他是 1991 年最佳新秀与全明星级得分手。",
 "dick cunningham": "“Cement Mixer（水泥搅拌机）”调侃其笨重却实用的内线风格。作为 60-70 年代皇家/雄鹿中锋，他是 1971 年夺冠的轮换。",
 "dick farley": "“Fearless（无畏）”为昵称。作为 60 年代尼克斯后卫，他是早期 NBA 的防守型角色。",
 "dick hemric": "“Dickie / Dixon（迪克森）”为昵称。作为 50-60 年代皇家/辛辛那提前锋，他是可靠的轮换得分手。",
 "dick schnittker": "“Sniff（嗅）”为昵称。作为 50 年代明尼阿波利斯湖人前锋，他是 1952-54 等冠的轮换。",
 "dick snyder": "“The Duck（鸭子）”为昵称。作为 70 年代骑士/勇士后卫，他是板凳组织者。",
 "dion waiters": "“Downhill Dion（下坡迪昂，形容其突破）/ Kobe Wade（科比·韦德，致敬梗）/ Google Me / Headache（头疼）/ Philly Cheese / Bubble Cheese”多为变体。作为后卫，他曾是骑士/雷霆的板凳火力点。",
 "don carlson": "“Swede（瑞典佬）”为昵称。作为 40-50 年代球员，他是早期 NBA 的轮换内线。",
 "don may": "“Donnie”为昵称。作为 60 年代末皇家/老鹰前锋，他是 1968 年最佳新秀。",
 "donte divincenzo": "“The Big Ragu（大拉古，借意面酱品牌）/ White Chocolate（白巧克力）/ DDV / DiVo / The Michael Jordan of Delaware（特拉华的乔丹）”多为变体。作为后卫，他 2021、2023 两夺总冠军（雄鹿、勇士）。",
 "earl cureton": "“The Twirl（旋转）”形容其转身的篮下动作。作为 80 年代活塞/火箭中锋，他是 1981、1989 等冠的板凳内线。",
 "ed nealy": "“Eddie”为昵称。作为 80-90 年代公牛/马刺前锋，他是蓝领板凳（1991 前后公牛轮换）。",
 "eddies johnson": "“Fast Eddie（快艾迪）/ E.J”形容其劲爆的转换进攻。作为 70-80 年代鹰/太阳前锋，他是全明星级得分手。",
 "eddies jones": "“E.J / Steady Eddie（稳健艾迪）”为昵称。作为 90-2000 年代湖人/热火后卫，他是 3D 样本与全明星。",
 "eddies jordan": "“Fast Eddie / Ed / Steady Eddie / Monty（蒙蒂）/ The Thief of Baghdad（巴格达神偷，借其盗球）/ The Thief”多为变体。作为 70 年代骑士后卫，他退役后成为名帅。",
 "eddy curry": "“Baby Shaq（小鲨鱼）”调侃他神似早年奥尼尔的壮硕身形。作为中锋，他是 00 年代公牛/尼克斯的低位得分手。",
 "elden campbell": "“Big E / Easy（轻松）”为昵称。作为 90-2000 年代湖人/活塞中锋，他是 2004 年活塞夺冠的板凳护框者。",
 "elton brand": "“E.B / Old School Chevy（老派雪佛兰）/ Horse（马）/ Slant / Chief Beef（牛肉酋长）”多为变体。作为快船/76 人中锋，他是全明星级内线与 2006 年最快进步球员。",
 "em bryant": "“Little Em（小艾姆）/ The Pest（捣蛋鬼）/ The Poet（诗人）”多为昵称。作为 60 年代尼克斯后卫，他是板凳组织者。",
 "eric moreland": "“E / Eazy-E（借说唱歌手梗）”为昵称。作为中锋，他是国王/猛龙等队的篮板型板凳。",
 "ernie beck": "“Boom Boom（轰轰）”形容其冲击篮下。作为 50-60 年代勇士/尼克斯前锋，他是 1956、1957 等冠的轮换。",
 "ernie digregorio": "“Ernie D / Ernie No D（无 D 艾尼，调侃其不投三分）”为昵称。作为 70 年代水牛城后卫，他是 1974 年最佳新秀。",
 "fennis dembo": "“Buck / Electric Man（电人）/ Fabulous（非凡）/ Dazzling Dude（炫目老兄）”多为变体。作为 80 年代末活塞前锋，他是“坏小子”时期的板凳火力。",
 "francisco elson": "“Geico（借车险广告梗）”为昵称。作为巴西中锋，他是 00 年代掘金/马刺的轮换内线。",
 "gabe pruitt": "“Smilin' Gabe（微笑加布）”为昵称。作为 00 年代末凯尔特人/尼克斯后卫，他是板凳新秀。",
 "gary bradds": "“Tex（德州佬）”为昵称。作为 60 年代末子弹前锋，他是轮换得分手。",
 "gary payton ii": "“The Mitten（手套二世）”玩他父亲“手套”加“连指手套”双关；“Young Glove（小手套）”则点出他承袭父号。作为后卫，他以防守韧性与板凳活力辗转多队。",
 "gary phillips": "“The Ghost（幽灵）/ Heave-Ho（嗨吼）”为昵称。作为 60 年代凯尔特人/老鹰后卫，他是 1964 年总冠军成员。",
 "gene conley": "“Long Gene（长吉恩）”形容其高瘦身形。作为 50-60 年代凯尔特人前锋，他是 1959、1960、1961 三冠成员，且是唯一同时打过 MLB 与 NBA 的球员。",
 "gene guarilia": "“Big Gene（大吉恩）”为身形昵称。作为 60 年代凯尔特人前锋，他是 1959-64 多冠时期的轮换。",
 "geoff petrie": "“Pistol Petrie（手枪皮特里）/ Rifle（来复枪）”形容其精准远投。作为 70 年代开拓者后卫，他是 1971 年最佳新秀与球队早期符号。",
 "george bucci": "“The King（国王）”为昵称。作为 70 年代尼克斯/骑士前锋，他是冠军队的角色内线。",
 "george king": "“Handsome George（帅乔）”为昵称。作为 60 年代锡拉丘兹后卫，他是 1955 年总冠军成员。",
 "george stone": "“Radar（雷达）/ Rocky（洛基）”为昵称。作为 60-70 年代前锋，他是 ABA/NBA 的轮换内线。",
 "gerald wallace": "“Crash（撞击）/ G-Force（G力）”形容他如撞击般拼命的防守与冲抢。作为山猫前锋，他是全明星级抢断与“赢球型”蓝领。",
 "glen davis": "“Big Baby（大宝贝）/ Large Infant（巨婴）/ Uno-Uno / Funk（芬克）”多为身形与性格梗。作为凯尔特人 2008 年夺冠的板凳内线，他以壮硕与激情闻名。",
 "happy hairston": "“Hap（哈普，快乐）/ Ax（斧）”为昵称。作为 60-70 年代皇家/老鹰前锋，他是篮板型角色球员。",
 "harrison barnes": "“Black Falcon（黑隼）/ Mr. 100%（百分先生）”多为变体。作为小牛/国王侧翼，他是 2015 年随勇士夺冠的稳定锋线。",
 "henry bibby": "“Instant Offense（即插进攻）”形容其板凳即战力。作为 70 年代尼克斯/76人后卫，他是 1973 年总冠军成员。",
 "herm gilliam": "“The Trickster（戏法师）”形容其狡猾的球风。作为 70 年代勇士/子弹前锋，他是 1975 年总冠军成员。",
 "howie schultz": "“Stretch（伸展）/ Steeple（尖塔）”为昵称。作为 50 年代明尼阿波利斯湖人前锋，他是球队早期多冠成员。",
 "iman shumpert": "“Shump（香普）”为昵称。作为尼克斯/骑士侧翼，他是 2016 年随骑士夺冠的防守尖兵。",
 "ira harge": "“Large（大）/ Hot Rod（热棒）/ The Big I（大I）”为昵称变体。作为 60 年代奇才/雄鹿中锋，他是 1968 年最佳新秀。",
 "isaiah hartenstein": "“iHart（i心）”为昵称。作为德裔中锋，他是 2024 年随凯尔特人夺冠的护框板凳。",
 "isaiah joe": "“Strokin' Joe（运指乔）/ Zai（宰）”为昵称。作为雷霆/76人射手，他以精准接球三分闻名。",
 "isaiah rider": "“J.R”为简称。作为 90 年代森林狼/开拓者后卫，他以华丽的“Rider Drop（骑马射）”扣篮闻名。",
 "ish smith": "“Ish（伊什）”为昵称。作为控卫，他辗转近 13 队、以速度与板凳组织闻名。",
 "j.j. barea": "“J.J”为姓名缩写。作为独行侠后卫，他是 2011 年随队夺冠的板凳发动机。",
 "j.r. smith": "“The Prodigy（神童）/ J.R. Swish（唰唰 JR）/ Henny God（亨尼神，借幽默梗）/ 911”多为变体。作为尼克斯/骑士后卫，他是 2016 年随骑士夺冠的激情射手。",
 "ja morant": "“G12”为昵称（名字 Ja + 12 号）。作为灰熊控卫，他是 2020 年最佳新秀与两届全明星，以滞空与暴力终结闻名。",
 "javale mcgee": "“Pierre（皮埃尔，自封法式名）/ The Big Secret（大秘密）/ Big Daddy Wookie（大老爹武基）/ The Great Adventure（大冒险）”多为自嘲变体。作为中锋，他三夺总冠军（勇士 2017、2018、湖人 2020），以“ fuck 时刻”迷因闻名。",
 "jack haley": "“Dude（老兄）”为昵称。作为 80-90 年代湖人/网队中锋，他是 1988 年总冠军板凳。",
 "jack mcmahon": "“Jack Mac / Irish（爱尔兰佬）/ Mac”为昵称。作为 50-60 年代皇家/湖人后卫，他是早期 NBA 的轮换控卫。",
 "jack nichols": "“Big Nick（大尼科）”为身形昵称。作为 50 年代华盛顿/凯尔特人前锋，他是 1959、1960 两冠成员。",
 "jackie butler": "“Paper（纸）”为昵称。作为 2000 年代马刺/火箭前锋，他是板凳内线。",
 "jackie moore": "“Jumping Jack（跳跃杰克）/ Jinx（霉运）”为昵称。作为 60-70 年代皇家/老鹰前锋，他是轮换内线。",
 "jacque vaughn": "“The Prince of Positivity（积极王子）”为昵称。作为马刺/篮网后卫，他是 2003、2005 两冠板凳，退役后成为教练。",
 "james edwards": "“Buddha（佛祖）”形容其沉稳与光头。作为 80-90 年代活塞/湖人中锋，他是 1989、1990 活塞与 1996、1997、1998 湖人等多冠板凳。",
 "james jones": "“JJ / Champ（冠军）/ JHoops”为昵称。作为神射侧翼，他是 2011（小牛）、2012、2013（热火）三夺总冠军的板凳更衣室领袖。",
 "james white": "“Flight（飞行）”形容其惊人的弹跳（曾 NBA 体测历史级纵跳）。作为 2000 年代板凳侧翼，他短暂效力多队。",
 "jaren jackson jr.": "“JJJ / Block Panther（封盖黑豹）”为昵称。作为灰熊中锋，他是 2019 年最佳防守球员，以护框与投射闻名。",
 "jason terry": "“The Jet（喷气机）/ JET”源自他飞快的第一步与名字 Jet 谐音；小牛 2011 夺冠的板凳尖刀，以关键三分与垃圾话闻名。生涯后期辗转多队，是著名的“更衣室毒瘤/赢球型老将”。",
 "jason williams": "“White Chocolate（白巧克力）”形容他如巧克力般丝滑华丽、却白皮肤的鬼魅传球；“J-Dub / J-Will / White Folks / The White Shadow（白影子）/ Duck / Showtime”多为变体。作为国王/热火控卫，他是 2006 年随热火夺冠的表演型组织者。",
 "jay miller": "“Jay Jay”为昵称。作为 70 年代骑士/火箭后卫，他是板凳角色。",
 "jaylin williams": "“Jay Will”为昵称。作为雷霆内线，他是新秀期以护框与策应立足的年轻中锋。",
 "jeff green": "“Uncle Jeff（杰夫叔叔）”为昵称。作为锋线，他辗转多队、2018 年随勇士夺冠，并以“换瓣”手术归来著称。",
 "jeremy lin": "“Linsanity（林疯狂）”是 2012 年他临危受命爆发、带领尼克斯连胜的疯狂风潮的代称，成为亚裔球员的文化符号；作为控卫，他是 2019 年随猛龙夺冠的板凳一员。",
 "jeremy sochan": "“The Destroyer（毁灭者）”为昵称。作为马刺侧翼，他以活力防守与多变发型闻名。",
 "jerome kersey": "“Romeo（罗密欧）/ Mercy Mercy（慈悲慈悲）/ Jerome Crazy（疯杰罗姆）/ The Cobra（眼镜蛇）”多为变体。作为开拓者前锋，他是 1990、1992 总决赛成员与 1999 年马刺夺冠的蓝领。",
 "jim barnes": "“Bad News（坏消息）”为昵称。作为 60-70 年代前锋，他是 1970 年尼克斯夺冠的板凳内线。",
 "jim chones": "“Bunny（兔仔）/ Aircraft Carrier（航母）”为昵称。作为 70-80 年代湖人/骑士中锋，他是 1980 年总冠军成员。",
 "jim loscutoff": "“Jungle Jim（丛林吉姆）/ Loscy”为昵称。作为 50-60 年代凯尔特人前锋，他是 7 届总冠军的硬汉蓝领（其 18 号因他退役而“退休”）。",
 "jim mcmillian": "“Butterball（黄油球）/ Floyd Butterball”为昵称。作为 70 年代湖人/子弹前锋，他是 1972 年总冠军成员。",
 "joakim noah": "“Jo / Sticks（木棍）”为昵称。作为公牛中锋，他是 2014 年最佳防守球员，以激情与封盖闻名。",
 "joe caldwell": "“Pogo（弹簧）/ Jumpin' Joe（跳跃乔）”形容其弹跳。作为 60-70 年代老鹰/太阳前锋，他是 1974 年 ABA 冠军成员。",
 "joe graboski": "“Grabbo（抓宝）”为昵称。作为 50-60 年代费城/活塞中锋，他是 1955 年总冠军成员。",
 "joe hassett": "“Joey / Sonar（声纳）”为昵称。作为 70-80 年代超音速/步行者后卫，他是板凳射手。",
 "joe kleine": "“Taco Joe（塔可乔）/ Smokin' Joe from Slater Mo（斯莱特磨坊的烟乔）”为昵称。作为中锋，他是 1998 年公牛夺冠的板凳。",
 "joel anthony": "“Warden（看守）/ Yaowa / Doc”为昵称。作为热火中锋，他是 2012、2013 两夺总冠军的护框板凳。",
 "john barnhill": "“Rabbit（兔）/ Barney（巴尼）”为昵称。作为 60 年代皇家/活塞后卫，他是 1968 年最佳新秀与轮换。",
 "john gianelli": "“G-Man”为昵称。作为 70 年代尼克斯/爵士中锋，他是轮换内线。",
 "john long": "“Johnny / Lightning（闪电）”为昵称。作为 80 年代活塞后卫，他是 1989、1990 两冠板凳火力。",
 "john paxson": "“Pax / Johnny Pax / Johnny”为昵称。作为公牛 90 年代三连冠控卫，他是 1993 年总决赛 G6 三分的“夺冠先生”，退役后任公牛总管。",
 "john salley": "“Spider（蜘蛛）/ Mr. May（五月先生，指季后赛）”为昵称。作为活塞 89、90 与公牛 96、97 四夺总冠军的板凳内线，他是罕有的“两王朝”成员。",
 "john starks": "“Starsky（斯塔斯基，借《警网双雄》角色）”为昵称。作为 90 年代尼克斯后卫，他是 1993 年全明星与“亲吻篮架”暴扣闻名。",
 "john trapp": "“John Q / The Q（Q先生）”为昵称。作为 70 年代湖人/骑士前锋，他是板凳轮换。",
 "john wall": "“Optimus Prime（擎天柱，变形金刚梗）/ Tupac（图帕克，借长相）”为昵称。作为奇才控卫，他是多届全明星与“沃尔时刻”的代言人。",
 "john warren": "“Johnny”为昵称。作为 70 年代骑士/篮网后卫，他是 ABA/NBA 的板凳角色。",
 "johnny davis": "“J.D”为昵称。作为 70 年代子弹/快船后卫，他是 1978 年总冠军成员。",
 "jordan bell": "“Eraser（橡皮）/ Swatterboy（灭蝇男孩）”为昵称。作为勇士/森林狼内线，他是 2018 年总冠军板凳。",
 "jordan clarkson": "“Flame Thrower（投火机）”形容他板凳即插的得分火力。作为第六人后卫，他 2020 年随湖人夺冠、以乱战得分闻名。",
 "jordan mcrea": "“Orange Mamba（橙色曼巴）”玩科比黑曼巴的变体（其大学田纳西配色橙）。作为得分后卫，他是辗转多队的板凳火力。",
 "jordan poole": "“The Microwave（微波炉）”形容他一上场就瞬间“加热”得分；“Swaggy Poole（摇摆普尔）/ JP3 / Poole Party（普尔派对）”多为变体。作为勇士 2022 年夺冠的板凳尖刀，他以乱战得分闻名。",
 "jose alvarado": "“Grand Theft Alvarado（大盗阿尔瓦拉多，借游戏 GTA 谐音）/ GTA”为球迷戏称，形容他如盗球机器般的抢断。作为鹈鹕控卫，他是板凳能量源。",
 "josh hart": "“Josh Barkley（乔什·巴克利）/ Hart of the City（城市之心，玩 Heart 谐音）”多为变体。作为后卫，他 2023 年随尼克斯闯总决赛、以拼抢与全能闻名。",
 "jud buechler": "“Mr. Fundamental（基本功先生）”玩邓肯外号的致敬梗。作为公牛 90 年代三连冠的板凳锋线，他是更衣室老将。",
 "justin holiday": "“The Fireman（消防员）”形容他替补上场“救火”的即插贡献。作为侧翼，他辗转多队、是可靠的轮换拼图。",
 "keith booth": "“Turk（土耳其佬）”为昵称。作为 90 年代子弹前锋，他是板凳得分手。",
 "kendrick perkins": "“Perk / Swamp Thing（沼泽怪物）”多为身形与出身（德州）梗。作为雷霆/凯尔特人中锋，他是 2008 年总决赛与 2016 骑士夺冠的蓝领护框者。",
 "kenny smith": "“The Jet（喷气机）”形容他飞快的第一步。作为火箭 90 年代双冠（1994、1995）控卫，他退役后成为名嘴解说（TNT）。",
 "kenrich williams": "“Kenny Hustle（肯尼·拼搏）”为昵称。作为侧翼，他是快船/老鹰等队的防守型轮换。",
 "kentavious caldwell-pope": "“K.C / Ken / KCP”为姓名简称变体。作为神射侧翼，他是 2017 年、2020 年两夺总冠军（勇士、湖人）的板凳火力。",
 "kermit washington": "“Special K / The Eagle（鹰）”为昵称。作为 70 年代湖人/开拓者前锋，他以防守与篮板闻名，也曾卷入 NBA 早期著名斗殴事件。",
 "kevin grevey": "“Greves / Grevo”为昵称。作为 70-80 年代子弹后卫，他是 1978 年总冠军成员与稳定射手。",
 "kevin mckenna": "“Opie”为昵称。作为 70-80 年代凯尔特人/步行者前锋，他是冠军队轮换。",
 "kevon looney": "“Loon（鹭）”为昵称。作为勇士内线，他是 2015、2017、2018、2022 四夺总冠军的挡拆与篮板支柱。",
 "kostas antetokounmpo": "“Greek Freak 2.0（希腊怪兽 2.0）”玩其兄扬尼斯的称号。作为字母哥之弟，他 2020 年随湖人圆梦夺冠。",
 "kurt rambis": "“Rambo（兰博）/ Clark Kent（克拉克·肯特，超人凡身）”多为变体（后者调侃他眼镜书生形象）。作为湖人 80 年代前锋，他是 1982、1985、1987、1988 多冠蓝领。",
 "kyle kuzma": "“Kuz（库兹）”为昵称。作为前锋，他是 2020 年湖人夺冠的年轻火力点，后以交易至奇才展开新篇。",
 "lamelo ball": "“Melo（甜瓜）”玩与卡梅隆·安东尼同号、也因父子同台梗。作为黄蜂控卫，他是 2020 年最佳新秀，以鬼魅传球闻名。",
 "lamar odom": "“L.O / Candy Man（糖果人）/ The Goods（好货）/ The Package（包裹）”多为变体。作为湖人前锋，他是 2009、2010 两夺总冠军的“第六人”样本。",
 "landry shamet": "“Lanbo / One a Day”为昵称。作为神射后卫，他辗转多队、以接球三分闻名。",
 "larry johnson": "“Grandmama（老奶奶）”来自他 Converse 广告中反串老奶奶的搞笑造型，成为 90 年代经典营销符号；作为黄蜂/尼克斯大前，他是多届全明星。",
 "larry nance": "“Little Hawk（小鹰）/ The High-Altolla of Slamola（灌篮高原）/ Flash Nance / Mr. Slambassador（灌篮大使）/ Flying Sun（飞日）”多为变体。作为骑士/太阳前锋，他是 1984 年首届扣篮大赛冠军。",
 "larry siegfried": "“Ziggy / Sieggy”为昵称。作为 60 年代凯尔特人后卫，他是多冠成员与替补大脑。",
 "larry steele": "“Man of Steal（盗球男）/ Bullet（子弹）”为昵称。作为 70 年代开拓者后卫，他是 1977 年夺冠的防守型控卫。",
 "latrell sprewell": "“Spree（斯普里）”为昵称。作为勇士/尼克斯后卫，他是全明星级得分手，曾因“锁喉教练”事件轰动联盟。",
 "leandro barbosa": "“The Brazilian Blur（巴西残影）/ Leandrinho（小莱昂）”形容他飞快的第一步。作为太阳/勇士后卫，他是 2007 年最佳第六人、2015 年随勇士夺冠。",
 "leon powe": "“The Show（大秀）”为昵称。作为凯尔特人前锋，他是 2008 年总冠军的板凳内线。",
 "lloyd neal": "“Ice（冰）”为昵称。作为 70 年代开拓者前锋，他是 1977 年夺冠的蓝领内线。",
 "luke kornet": "“The Green Kornet（绿 Kornet，玩广播剧《绿黄蜂》谐音）/ UniKornet（独角兽）/ Korn on the Lob（挡拆玉米）/ The Big Elote（大玉米，西语）”多为变体。作为内线，他 2024 年随凯尔特人夺冠。",
 "luke walton": "“Little Wheats（小惠茨）”为昵称（源自麦片广告）。作为湖人 2009、2010 两冠前锋，退役后成为勇士/湖人教练。",
 "luol deng": "“The Man from Sudan（苏丹来客）/ Deng-erous（危险邓，玩 dangerous 谐音）”点出他的南苏丹出身。作为公牛/热火侧翼，他是两届全明星防守锋线。",
 "malik rose": "“Shaq of the MAC（MAC 的鲨鱼）”玩奥尼尔梗（MAC 指其大学联盟）。作为马刺前锋，他是 1999、2003 两夺总冠军的板凳内线。",
 "marc iavaroni": "“Psycho（精神哥）”为昵称。作为马刺前锋，他是 2007 年夺冠的轮换锋线，后成为助教。",
 "marco belinelli": "“Beli / The Professional（职业枪手）”多为变体。作为意大利射手，他是 2014 年随马刺夺冠、并拿下 2013 年三分大赛冠军。",
 "mario chalmers": "“Super Mario（超级马里奥，借游戏）/ The Superintendent（管家）/ Rio（里约，巴西出身）”多为变体。作为热火控卫，他是 2006、2012、2013 三夺总冠军的关键后卫。",
 "mario elie": "（见上 Ninja）",
 "mark jackson": "“Action（行动）”为其球员时代昵称（呼应后来菲尔·杰克逊同名梗）。作为 90 年代尼克斯/步行者控卫，他是联盟助攻前列的“球员兼解说”样本。",
 "mark madsen": "“Mad Dog（疯狗）”形容其拼抢。作为湖人 2001、2002 两冠前锋，他是蓝领板凳，退役后成为教练。",
 "mark mcnamara": "“Tank（坦克）/ The Snake（蛇）”为昵称。作为 80 年代超音速/马刺中锋，他是冠军队轮换。",
 "markieff morris": "“Keef / Smooth（丝滑）/ Snoop Dogg（史努比狗，借长相）”多为变体。作为大前，他是 2021 年随雄鹿夺冠的板凳火力。",
 "marreese speights": "“Mo / Mo' Buckets（进球莫）”为昵称。作为勇士中锋，他是 2015 年夺冠的板凳得分手。",
 "marvin barnes": "“Bad News（坏消息）/ The Magnificent（宏伟）/ Movin' Marvin（动感马文）/ BB”多为变体。作为 ABA/NBA 前锋，他是 70 年代篮网 ABA 冠军成员、以暴力著称。",
 "matt bonner": "“Red Rocket（红火箭）/ Red Mamba（红曼巴，玩科比梗）/ Sandwich Hunter（三明治猎人）/ Coach 'B'”多为变体。作为马刺前锋，他是 2007、2014 两冠的神射板凳。",
 "matt guokas": "“Matty / The Phantom（幻影）”为昵称。作为 60-70 年代 76 人/勇士中锋，他是 1967 年总冠军成员。",
 "matthew dellavedova": "“Delly / Outback Jesus（内陆耶稣，玩澳洲内陆梗）”为昵称。作为澳大利亚控卫，他是 2016 年骑士夺冠的拼命板凳。",
 "mccoy mclemore": "“Mac（麦克）”为昵称。作为国王/灰熊后卫，他是轮换三分火力。",
 "med park": "“Bulldozer from Missouri（密苏里推土机）/ Missouri Mule（密苏里骡）/ Bulldozer / Rocket（火箭）”多为变体。作为 50 年代明尼阿波利斯湖人前锋，他是多冠成员。",
 "mel counts": "“Goose（鹅）/ Dr. C（C 博士）”为昵称。作为 60 年代辛辛那提皇家前锋，他是轮换内线。",
 "mel hutchins": "“Hutch（哈奇）”为昵称。作为 50 年代活塞/尼克斯中锋，他是全明星级篮板手。",
 "mengke bateer": "“Dinosaur（恐龙）”为昵称（借其大学新疆背景与身形）。作为火箭/森林狼中锋，他是 2002 年最佳新秀、辗转多队的板凳内线。",
 "michael doleac": "“Mike（迈克）”为昵称。作为中锋，他是 2006 年随热火夺冠的板凳。",
 "michael porter jr.": "“MPJ / Showtime（秀场）/ Never Swing the Rock（永不甩锅）”多为变体。作为掘金前锋，他是 2023 年随队首夺总冠军的火力点。",
 "michael ray richardson": "“Sugar Ray（糖·雷）/ Mike（迈克）”为昵称。作为 80 年代勇士/网队后卫，他是全明星级助攻/抢断手，却因禁药早早退场。",
 "mike conley": "“Money Mike（金钱迈克）/ Mountain Mike（山迈克）/ Bite Bite（咬咬）”多为变体。作为灰熊/森林狼控卫，他是多届全明星与稳健组织者。",
 "mike james": "“Pit Bull（比特犬）/ The Amityville Horror（阿米蒂维尔惊魂，借电影）”玩其凶悍与姓氏梗。作为控卫，他辗转多队、以得分爆发力闻名。",
 "mike mcgee": "“Geeter / The Offensive Machine（进攻机器）/ Little Mac（小麦克）”多为变体。作为湖人 80 年代后卫，他是 1982、1985、1987、1988 多冠板凳火力。",
 "mike smrek": "“Diesel（柴油）”玩奥尼尔同号梗（身形相似）。作为湖人/马刺中锋，他是 2000、2001、2002、2003 等多冠板凳。",
 "miles mcbride": "“Deuce（双二）”为昵称。作为尼克斯控卫，他是年轻板凳防守者。",
 "milt wagner": "“Ice（冰）”为昵称。作为 80 年代超音速/篮网后卫，他是板凳火力。",
 "mitch kupchak": "“The Kupper / The Kup”为昵称。作为湖人 80 年代前锋，他是 1980、1982、1985、1987、1988 多冠成员，退役后成为湖人传奇总管。",
 "mitchell robinson": "“Block Ness Monster（封盖尼斯怪）/ Lobinson（空接罗宾逊）/ Big Country（大乡下）”多为变体。作为尼克斯中锋，他以遮天蔽日护框与空接闻名。",
 "mookie blaylock": "“The Thief（盗贼）”形容他历史级的抢断。作为 90 年代老鹰控卫，他是全明星级防守组织者。",
 "mychal thompson": "“Bells（钟）/ Sweet Bells（甜钟）”为昵称。作为 80 年代湖人前锋，他是 1987、1988 两冠内线，也是克莱·汤普森之父。",
 "nate bowman": "“The Snake（蛇）/ Nate the Skate（旱冰奈特）”为昵称。作为 60 年代尼克斯中锋，他是 1970、1973 两冠成员。",
 "nazr mohammed": "“Naz / Nasty（脏）/ Big Nasty（大脏）/ Big Z（大 Z）”多为变体。作为中锋，他是 2005 年随马刺夺冠的板凳护框者。",
 "nemanja bjelica": "“Professor Big Shots（绝杀教授）/ Belly（肚）”为昵称。作为塞尔维亚前锋，他是 2022 年随勇士夺冠的空间型板凳。",
 "norm van lier": "“Stormin' Norman（风暴诺曼）/ The Storm（风暴）”形容他硬朗的防守。作为 70 年代公牛后卫，他是多届全明星与球队大脑。",
 "norris cole": "“Cole Train（科尔列车）”为昵称。作为热火控卫，他是 2012、2013 两夺总冠军的板凳组织者。",
 "otto porter jr.": "“Bubba / O”为昵称。作为锋线，他是 2018 年随奇才、后在勇士的轮换射手。",
 "p.j. tucker": "“Tuck Wagon（塔克货车）”为昵称。作为矮壮锋线，他是 2021 年随雄鹿夺冠的防守粘合剂，以锁死箭头闻名。",
 "pat connaughton": "“Vanilla Thunder（香草雷霆）/ Planet Pat（帕特星球）”多为变体。作为后卫，他是 2021 年随雄鹿夺冠的板凳能量源。",
 "patrick mccaw": "“Pat（帕特）”为昵称。作为勇士侧翼，他是 2017、2018 两冠板凳，后以发展联盟逆袭闻名。",
 "patty mills": "“Patty Cakes（帕蒂蛋糕）/ Pat Stacks（帕特堆）”为昵称。作为澳洲控卫，他是 2014 年随马刺夺冠的板凳火力与更衣室灵魂。",
 "paul millsap": "“The Anchor man（锚人）”形容他如锚般稳固的低位。作为大前，他是多届全明星与老鹰“锋线四人组”核心。",
 "payton pritchard": "“Fast PP（快 PP）/ 8 Mile（八英里，借电影）/ P-Rabbit（P 兔）”多为变体。作为凯尔特人控卫，他是 2024 年夺冠的板凳组织者。",
 "pete chilcutt": "“Chili Pete（辣椒皮特）”为昵称。作为 90 年代超音速/爵士前锋，他是板凳内线。",
 "peyton watson": "“Swatson（盖沃森，玩 swat 盖帽）”为昵称。作为掘金后卫，他是 2023 年随队首夺总冠军的年轻板凳。",
 "phil hankinson": "“Spider（蜘蛛）”形容其长臂覆盖。作为 70 年代老鹰/凯尔特人前锋，他是 1976 年总冠军成员。",
 "phil walker": "“Grump（脾气佬）”为昵称。作为 70 年代 76 人/水牛城前锋，他是板凳轮换。",
 "quinn cook": "“Q”为姓名缩写。作为控卫，他是 2018 年随勇士夺冠的板凳组织者。",
 "ray felix": "“Baby Ray（宝贝雷）/ The Count（伯爵）”为昵称。作为 50-60 年代中锋，他是 1958 年最佳新秀。",
 "reggie jackson": "“Mr. June（六月先生，指季后赛爆发）/ Big Government（大政府）”多为变体。作为后卫，他是 2023 年随天使（棒球？不）—实际他是 NBA 板凳得分手，以常规赛末段爆发闻名。",
 "reggie johnson": "“Grady（格雷迪）”为昵称。作为 70 年代超音速/马刺中锋，他是板凳内线。",
 "rich parks": "“Richie（里奇）”为昵称。作为 70 年代骑士/篮网前锋，他是轮换内线。",
 "richard jefferson": "“R.J”为简称。作为侧翼，他是 2003 年网队总决赛、2016 年随骑士夺冠的轮换锋线。",
 "richard petruska": "“Rich（里奇）”为昵称。作为 90 年代火箭/森林狼中锋，他是板凳内线。",
 "rick carlisle": "“Flipper（鳍）/ Flip（翻）”为昵称。作为球员他是 80 年代凯尔特人冠军队板凳，后以教练身份两度率队进总决赛、2011 年带小牛夺冠。",
 "rick fox": "“Foxy（福克斯，借姓氏 Fox 狐狸）/ Blondie（金发）”为昵称。作为湖人/凯尔特人侧翼，他是 2000、2001、2002 三夺总冠军的更衣室领袖。",
 "rick mount": "“The Rocket（火箭）”形容其精准远投。作为 60-70 年代后卫，他是大学传奇射手与短暂 NBA 生涯。",
 "robert horry": "“Big Shot Rob（关键球鲍勃）/ Big Shot Bob / The Key Man（关键先生）”来自他七次夺冠历程中无数次关键绝杀；作为马刺/湖人/火箭的“季后赛赢家”，他是历史上夺冠最多的角色球员之一。",
 "robin jones": "“Rubberband Man（橡皮筋人）”形容其柔韧身手。作为 70 年代骑士/开拓者中锋，他是 1977 年夺冠的板凳内线。",
 "ron bonham": "“Muncie Mortar（曼西迫击炮）/ Blond Bomber（金发轰炸机）”为昵称。作为 60 年代辛辛那提皇家前锋，他是 1963 年总冠军成员。",
 "ron harper": "“Hollywood（好莱坞）/ Ohio Flyer（俄亥俄飞人）/ Harp（哈普）”多为变体。作为后卫，他是公牛 90 年代三连冠与湖人 2000-2002 三连冠的“双三连冠”老将。",
 "ron thomas": "“The Plumber（水管工）/ Duck（鸭）”为昵称。作为 70 年代尼克斯前锋，他是 1970、1973 两冠板凳。",
 "rudy gobert": "“The Stifle Tower（窒息塔）”形容他遮天蔽日的护框；“The French Rejection（法国拒绝，玩 dunk 被盖梗）/ The Gobert Report（戈贝尔报告）/ Gobzilla（戈贝拉，玩哥斯拉）/ Big Ru”多为变体。作为法国中锋，他是多届最佳防守球员、2021 年随爵士与法国队登顶。",
 "rudy larusso": "“Deuce / The Ivy Leaguer With Muscles（有肌肉的常春藤学霸）/ Honey Boy（蜜男孩）/ Musty / Brutus / Roughhouse Rudy（粗汉鲁迪）”多为变体。作为 60 年代湖人前锋，他是多届全明星与冠军队成员。",
 "russ critchfield": "“Rusty（锈）”为昵称。作为 60-70 年代超音速/火箭后卫，他是板凳组织者。",
 "sam merrill": "“Sammy Buckets（进球萨米）/ Money Merrill（金钱梅里尔）”为昵称。作为射手，他是 2021 年随雄鹿夺冠的板凳火力。",
 "sasha kaun": "“Sasha（萨沙）”为昵称。作为俄罗斯中锋，他是 2016 年随骑士夺冠的板凳内线。",
 "sasha vujacic": "“The Machine（机器）”形容他稳定冷面的投射。作为湖人后卫，他是 2009、2010 两夺总冠军的板凳射手。",
 "scot pollard": "“Samurai Scot（武士斯科特）”为昵称（源自其亚裔长相玩笑）。作为内线，他是 2008 年随凯尔特人夺冠的板凳奇兵。",
 "scott brooks": "“Wonderdog（神犬）”为昵称。作为 90 年代 76 人/森林狼后卫，他是 1999 年随马刺夺冠的板凳，退役后成为名帅（雷霆）。",
 "scott williams": "“Tank（坦克）”为昵称。作为内线，他是 1991、1992、1993 公牛三连冠的板凳护框者。",
 "shandon anderson": "“Rod（罗德）”为昵称。作为侧翼，他是 1995、1996、1997、2000 等多冠（火箭、湖人）的板凳锋线。",
 "shaun livingston": "“S Dot（S 点）”为昵称。作为控卫，他是 2015、2017、2018 三夺总冠军的勇士“死亡五小”板凳大脑，以长臂组织闻名。",
 "stacey king": "“Sky（天空）/ Pearl（珍珠）”为昵称。作为公牛 90 年代中锋，他是 1991、1992、1993 三连冠的板凳火力（解说名言“He's on fire!”）。",
 "stanislav medvedenko": "“Slava（斯拉瓦）”为昵称。作为乌克兰前锋，他是 2001、2002 年湖人两冠板凳。",
 "stephen jackson": "“Cap'n Jack（船长杰克）/ Stack Jack（叠杰克）”为昵称。作为侧翼，他是 2003 年随马刺夺冠的板凳火力，以硬朗与争议闻名。",
 "steve francis": "“Stevie Franchise（特许史蒂夫，借其名字 Franchise 梗）/ Wink（眨）/ City（城市）”多为变体。作为火箭控卫，他是多届全明星与“姚麦时代”发动机。",
 "steve kerr": "“Ice（冰）”形容其冷血关键球。作为公牛/马刺后卫，他是多冠射手（1996-99 公牛、2003 马刺），退役后成为勇士名帅（多冠）。",
 "steve kuberski": "“The Polish Powerhouse（波兰动力舱）”玩其波兰血统梗。作为 70 年代凯尔特人中锋，他是 1974、1976 两冠板凳。",
 "svi mykhailiuk": "“Ukraine Maker（乌克兰制造）”点出其出身。作为侧翼，他是 2023 年随活塞/后来交易的板凳，辗转多队。",
 "talen horton-tucker": "“THT”为姓名缩写。作为侧翼，他是湖人/爵士等队的年轻轮换。",
 "terry cummings": "“Preacher（传教士）/ T.C”为昵称。作为大前，他是 1985 年最佳新秀与多届全明星（雄鹿/快船）。",
 "terry duerod": "“Sweet Due（甜杜）”为昵称。作为 80 年代活塞/独行侠后卫，他是板凳火力。",
 "thanasis antetokounmpo": "“Thanasty（萨纳斯蒂）”玩其名 Thanasis 与 nasty（脏/狠）谐音。作为字母哥之兄，他是 2021 年雄鹿夺冠的板凳能量与防守尖兵。",
 "timofey mozgov": "“Mozzy（莫齐）”为昵称。作为俄罗斯中锋，他是 2016 年随骑士夺冠的护框板凳。",
 "tony campbell": "“Top Cat（顶级猫）/ T.C / Blumpy（肿块）”多为变体。作为 90 年代活塞/森林狼后卫，他是板凳火力。",
 "tony massenburg": "“Hercules（赫拉克勒斯）/ T-Mass”为昵称。作为内线，他是 1995 年随火箭夺冠、辗转创纪录多队的板凳。",
 "trent tucker": "“Doc（博士）”为昵称。作为 80-90 年代尼克斯后卫，他是板凳射手（曾命中著名的“0.1 秒”绝杀）。",
 "trevor ariza": "“Switchblade（弹簧刀）”形容其长臂切换防守。作为侧翼，他是 2009 年随湖人夺冠、后多次效力的防守拼图。",
 "tristan thompson": "“Double T（双 T）”为昵称。作为骑士中锋，他是 2016 年总冠军的篮板狂人与更衣室核心。",
 "tyronn lue": "“Lue Heffner（卢·亨夫纳，借漫画）”为昵称。作为湖人 90 年代后卫，他是 2000、2001 两冠板凳，退役后成为 2016 骑士夺冠教头。",
 "udonis haslem": "“U.D / UD-40 / Mr. 305（305 先生，迈阿密区号）/ The Mayor of Miami（迈阿密市长）”多为变体。作为热火内线，他是队史象征、2006、2012、2013 三夺总冠军的更衣室领袖。",
 "vernon maxwell": "“Hawk（鹰）/ Mad Max（疯麦克斯）”为昵称。作为火箭后卫，他是 1994、1995 两连冠的板凳火力与“关键先生”。",
 "victor oladipo": "“Dipo（迪波）”为昵称。作为步行者/热火后卫，他是全明星级防守后卫与 2018 年年度最佳防守阵容、2019 年进步最快球员。",
 "vinnie johnson": "“Microwave（微波炉，一上场即热）/ V.J / Hoo / Mookie / 007”多为变体。作为活塞“坏小子”后卫，他是 1989、1990 两冠的板凳尖刀，以即插得分闻名。",
 "wali jones": "“Wally / Wally Wonder（神奇沃利）/ Robin（罗宾）/ Sugar Bear（糖熊）”多为变体。作为 60-70 年代子弹/76 人后卫，他是 1967 年总冠军成员。",
 "wally osterkorn": "“Ox（公牛）”为昵称。作为 50-60 年代皇家/尼克斯前锋，他是轮换内线。",
 "wally walker": "“Wally Wonder / Wally Wonderful（神奇沃利）”为昵称。作为 70 年代子弹/火箭前锋，他是 1978 年总冠军成员。",
 "walt davis": "（见上 Walt）",
 "wes matthews": "“Wild Wild Wes（狂野韦斯）”为昵称。作为 80 年代老鹰/雄鹿后卫，他是 1984 年最佳新秀与冠军队板凳。",
 "will perdue": "“Will Vanderbilt（范德堡威尔，借其大学）”为昵称。作为中锋，他是 1999 年随马刺夺冠的板凳护框者。",
 "william bedford": "“Willie B / Bed（床）”为昵称。作为 80-90 年代活塞/马刺中锋，他是冠军队板凳。",
 "willie sojourner": "“Willie / Rainbow（彩虹）”为昵称。作为 70 年代超音速/子弹前锋，他是板凳内线。",
 "win wilfong": "“Winnie（温尼）”为昵称。作为 50 年代皇家/老鹰后卫，他是轮换角色。",
 "billy donovan": "“Billy the Kid（小比利）”是对他名字的俏皮叫法。作为球员他只是 1987 年落选末段被选中的短命控卫，真正成名是在教练席——率领佛罗里达大学两夺 NCAA 冠军（2006、2007），后执掌多支 NBA 球队，并入选篮球名人堂。",
 "eddie johnson": "“Fast Eddie（快枪埃迪）”点出他第一步之快与 burst 式得分能力。作为老鹰/超音速的锋卫摇摆人，他是 70 年代末至 80 年代的两次全明星与两次最佳防守阵容成员。",
 "eddie jones": "“Steady Eddie（稳健埃迪）”概括了他攻防一体的可靠边翼属性——三届全明星、多次最佳防守阵容，并在 1999-2000 赛季荣膺联盟抢断王。",
 "eddie jordan": "“Fast Eddie（快枪埃迪）”形容他作为后卫的速度；资料中还列有 Ed、Steady Eddie、Monty 以及较冷门的 The Thief of Baghdad 等变体。作为 80 年代湖人后卫，他随队夺得 1982 年总冠军。",
 "jordan mcrae": "“Orange Mamba（橙色曼巴）”是借科比“Black Mamba（黑曼巴）”玩的谐音/意象，呼应其田纳西“Vols（橙色）”底色与得分型后卫的风格；他曾位列 2016 年克利夫兰冠军阵容、获一枚总冠军戒指。",
 "kristaps porzingis": "“Unicorn（独角兽）”由凯文·杜兰特在 2015 年的一档播客中大名鼎鼎地喊出——一个 7 尺 3 寸却能像后卫一样投三分、护框的七尺长人，彼时如“独角兽”般稀有；“Zinger”则取自其姓氏。他是 2024 年 NBA 总冠军成员。",
 "shawn marion": "“The Matrix（矩阵/黑客帝国）”成名于他生涯早期——那种古怪、超 athletic、一抖一抖的打法看起来几乎像被“数字渲染”出来，令人联想到电影；其姓氏 Marion 也与 Matrix 谐音。他是四届全明星，并在 2011 年随达拉斯夺冠。",
 "world b. free": "他本名 Lloyd Free，因崇拜“自由”于 1979 年合法改名为 World B. Free；“The Prince of Mid-Air（半空王子）”形容他飞天遁地的扣篮。",
 "blake griffin": "“High Griffinition”玩了“definition”的谐音，形容他夸张的弹跳与扣篮定义；“BG”为名字缩写。",
 "allen iverson": "“The Answer（答案）”是他 1996 年进入联盟时被赋予的代号，寓意“球队所有问题的解答”；“AI”为缩写，“Bubba Chuck”是他自述的街头本名。",
 "muggsy bogues": "“Muggsy”是童年昵称；身高仅 5 尺 3 寸（1.60m）却是 NBA 历史最矮球员，却以速度掩盖身高。",
 "nate archibald": "“Tiny”与他 6 尺 1 的精悍身材形成反差（实则并不矮小，只是昵称）；“Nate the Great”致敬推理童书主角，形容他的大心脏。",
 "zach randolph": "“Z-Bo”为名字缩写与童年昵称“Bo”的组合；灰熊“磨坊进攻”的低位核心。",
 "doc rivers": "“Doc”来自他本名 Glenn，少年时戴眼镜、一副“医生”模样，朋友遂叫“Doc”，沿用为代号。",
 "james worthy": "“Big Game James（大场面詹姆斯）”来自他总决赛屡建奇功、三次获 MVP 的关键先生本色。",
 "shawn kemp": "“Reign Man（统治者）”原为电台主播口误把“Rim Man（篮筐人）”说错，反倒成了他暴力扣将的完美代号。",
 "metta world peace": "“The Ron-Ron”为早期昵称；2011 年他合法改名为 Metta World Peace（世界和平），以宣扬反暴力，成为 NBA 更名奇观。",
 "ron artest": "“The Ron-Ron”为早期昵称；2011 年他合法改名为 Metta World Peace（世界和平），以宣扬反暴力，成为 NBA 更名奇观。",
 "gilbert arenas": "“Agent Zero（零号特工）”来自他身披的 0 号球衣与特工片般的冷血关键球气质。",
 "zydrunas ilgauskas": "“Big Z”为名字首字母与身高（2.21m）的合称；骑士队史效力最久的中锋之一。",
 "spud webb": "“Spud”为童年昵称；身高仅 5 尺 7 寸（1.70m）却在 1986 年全明星扣篮大赛夺冠，成为小个子扣篮传奇。",
 "anfernee hardaway": "“Penny”为他本名 Anfernee 的昵称（母亲所起）；“Little Penny”则来自他 Nike 广告中与之对话的迷你玩偶形象。",
 "penny hardaway": "“Penny”为他本名 Anfernee 的昵称（母亲所起）；“Little Penny”则来自他 Nike 广告中与之对话的迷你玩偶形象。",
 "demarcus cousins": "“Boogie”为名字 DeMarcus 的昵称变体；国王/鹈鹕时期暴力低位核心。",
}
