-- migrate_team_lineups.sql
-- BR 球队 Lineups 页（#lineups_5-man_）实为「整队 5 人阵容的净差值(Net)统计」表，
-- 列集为 mp + diff_pts / diff_fg_pct / diff_orb ...（非 gp/won/lost/pts/off_rtg 等
-- 原推断列）。改为存储净差值，保留 5 人组合槽位与 (team_abbr,season,season_type,lineup_key) 主键。
-- 表为空，直接 ALTER 列即可（保留 id 序列与现主键）。

ALTER TABLE team_lineups
    DROP COLUMN IF EXISTS gp,
    DROP COLUMN IF EXISTS minutes,
    DROP COLUMN IF EXISTS won,
    DROP COLUMN IF EXISTS lost,
    DROP COLUMN IF EXISTS pts,
    DROP COLUMN IF EXISTS opp_pts,
    DROP COLUMN IF EXISTS off_rtg,
    DROP COLUMN IF EXISTS def_rtg,
    DROP COLUMN IF EXISTS net_rtg;

ALTER TABLE team_lineups
    ADD COLUMN IF NOT EXISTS mp TEXT,
    ADD COLUMN IF NOT EXISTS diff_pts DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_fg DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_fga DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_fg_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_fg3 DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_fg3a DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_fg3_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_efg_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_ft DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_fta DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_ft_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_orb DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_orb_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_drb DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_drb_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_trb DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_trb_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_ast DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_stl DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_blk DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_tov DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS diff_pf DOUBLE PRECISION;
